/**
 * Marlin 3D Printer Firmware
 * Copyright (C) 2016 MarlinFirmware [https://github.com/MarlinFirmware/Marlin]
 *
 * Based on Sprinter and grbl.
 * Copyright (C) 2011 Camiel Gubbels / Erik van der Zalm
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

/**
 * Czech
 * UTF-8 for Graphical Display
 *
 * LCD Menu Messages
 * See also http://marlinfw.org/docs/development/lcd_language.html
 *
 * Translated by Petr Zahradnik, Computer Laboratory
 * Blog and video blog Zahradnik se bavi
 * http://www.zahradniksebavi.cz
 *
 */
#ifndef LANGUAGE_CZ_UTF_H
#define LANGUAGE_CZ_UTF_H

#define MAPPER_C3C4C5_CZ
#define DISPLAY_CHARSET_ISO10646_CZ

#define WELCOME_MSG                         MACHINE_NAME _UxGT(" p鑹praven.")
#define MSG_BACK                            _UxGT("Zp鑷巘")
#define MSG_SD_INSERTED                     _UxGT("Karta vlo鍟猠na")
#define MSG_SD_REMOVED                      _UxGT("Karta vyjmuta")
#define MSG_LCD_ENDSTOPS                    _UxGT("Endstopy") // max 8 znaku
#define MSG_MAIN                            _UxGT("Hlavn閾� nab閾哾ka")
#define MSG_AUTOSTART                       _UxGT("Autostart")
#define MSG_DISABLE_STEPPERS                _UxGT("Uvolnit motory")
#define MSG_DEBUG_MENU                      _UxGT("Nab閾哾ka lad鑷巒閾�")
#define MSG_PROGRESS_BAR_TEST               _UxGT("Test uk. pr鏆朾鑷巋u")
#define MSG_AUTO_HOME                       _UxGT("Domovsk璋� pozice")
#define MSG_AUTO_HOME_X                     _UxGT("Dom鏆� osa X")
#define MSG_AUTO_HOME_Y                     _UxGT("Dom鏆� osa Y")
#define MSG_AUTO_HOME_Z                     _UxGT("Dom鏆� osa Z")
#define MSG_LEVEL_BED_HOMING                _UxGT("M鑷庤墶en閾� podlo鍟猭y")
#define MSG_LEVEL_BED_WAITING               _UxGT("Kliknut閾唌 spus閽畉e")
#define MSG_LEVEL_BED_NEXT_POINT            _UxGT("Dal鎷ч搯 bod")
#define MSG_LEVEL_BED_DONE                  _UxGT("M鑷庤墶en閾� hotovo!")
#define MSG_Z_FADE_HEIGHT                   _UxGT("V濯掓嫥ka srovn璋﹙璋﹏閾�")
#define MSG_SET_HOME_OFFSETS                _UxGT("Nastavit ofsety")
#define MSG_HOME_OFFSETS_APPLIED            _UxGT("Ofsety nastaveny")
#define MSG_SET_ORIGIN                      _UxGT("Nastavit po鑶疯癌tek")
#define MSG_PREHEAT_1                       _UxGT("Zah鑹¤癌t PLA")
#define MSG_PREHEAT_1_N                     MSG_PREHEAT_1 _UxGT(" ")
#define MSG_PREHEAT_1_ALL                   MSG_PREHEAT_1 _UxGT(" v鎷")
#define MSG_PREHEAT_1_END                   MSG_PREHEAT_1 _UxGT(" hotend")
#define MSG_PREHEAT_1_BEDONLY               MSG_PREHEAT_1 _UxGT(" podlo鍟�")
#define MSG_PREHEAT_1_SETTINGS              MSG_PREHEAT_1 _UxGT(" nast")
#define MSG_PREHEAT_2                       _UxGT("Zah鑹¤癌t ABS")
#define MSG_PREHEAT_2_N                     MSG_PREHEAT_2 _UxGT(" ")
#define MSG_PREHEAT_2_ALL                   MSG_PREHEAT_2 _UxGT(" v鎷")
#define MSG_PREHEAT_2_END                   MSG_PREHEAT_2 _UxGT(" hotend")
#define MSG_PREHEAT_2_BEDONLY               MSG_PREHEAT_2 _UxGT(" podlo鍟�")
#define MSG_PREHEAT_2_SETTINGS              MSG_PREHEAT_2 _UxGT(" nast")
#define MSG_COOLDOWN                        _UxGT("Zchladit")
#define MSG_SWITCH_PS_ON                    _UxGT("Zapnout nap璋﹋en閾�")
#define MSG_SWITCH_PS_OFF                   _UxGT("Vypnout nap璋﹋en閾�")
#define MSG_EXTRUDE                         _UxGT("Vytla鑶穒t (extr.)")
#define MSG_RETRACT                         _UxGT("Zatla鑶穒t (retr.)")
#define MSG_MOVE_AXIS                       _UxGT("Posunout osy")
#define MSG_BED_LEVELING                    _UxGT("Vyrovnat podlo鍟猭u")
#define MSG_LEVEL_BED                       _UxGT("Vyrovnat podlo鍟猭u")
#define MSG_LEVEL_CORNERS                   _UxGT("Vyrovnat rohy")
#define MSG_NEXT_CORNER                     _UxGT("Dal鎷ч搯 roh")
#define MSG_EDITING_STOPPED                 _UxGT("Konec 鐓rav s閾唗鑷�")

#define MSG_UBL_DOING_G29                   _UxGT("Prov璋ヾ閾唌 G29")
#define MSG_UBL_UNHOMED                     _UxGT("P鑹je鑶箃e dom鏆�")
#define MSG_UBL_TOOLS                       _UxGT("UBL n璋﹕troje")
#define MSG_UBL_LEVEL_BED                   _UxGT("Unified Bed Leveling")
#define MSG_UBL_MANUAL_MESH                 _UxGT("Manu璋﹍n閾� s閾嗛挳 bod鏆�")
#define MSG_UBL_BC_INSERT                   _UxGT("Vlo鍟猼e kartu, zm鑷庤墶te")
#define MSG_UBL_BC_INSERT2                  _UxGT("Zm鑷庤墶te")
#define MSG_UBL_BC_REMOVE                   _UxGT("Odstra鑹宼e a zm鑷庤墶te")
#define MSG_UBL_MOVING_TO_NEXT              _UxGT("P鑹sun na dal鎷ч搯")
#define MSG_UBL_ACTIVATE_MESH               _UxGT("Aktivovat UBL")
#define MSG_UBL_DEACTIVATE_MESH             _UxGT("Deaktivovat UBL")
#define MSG_UBL_SET_BED_TEMP                _UxGT("Teplota podlo鍟猭y")
#define MSG_UBL_CUSTOM_BED_TEMP             MSG_UBL_SET_BED_TEMP
#define MSG_UBL_SET_HOTEND_TEMP             _UxGT("Teplota hotendu")
#define MSG_UBL_CUSTOM_HOTEND_TEMP          MSG_UBL_SET_HOTEND_TEMP
#define MSG_UBL_MESH_EDIT                   _UxGT("鑴穚rava s閾唗鑷� bod鏆�")
#define MSG_UBL_EDIT_CUSTOM_MESH            _UxGT("Upravit vlastn閾� s閾嗛挳")
#define MSG_UBL_FINE_TUNE_MESH              _UxGT("Doladit s閾嗛挳 bod鏆�")
#define MSG_UBL_DONE_EDITING_MESH           _UxGT("Konec 鐓rav s閾唗鑷�")
#define MSG_UBL_BUILD_CUSTOM_MESH           _UxGT("Vlastn閾� s閾嗛挳")
#define MSG_UBL_BUILD_MESH_MENU             _UxGT("Vytvo鑹t s閾嗛挳")
#define MSG_UBL_BUILD_PLA_MESH              _UxGT("S閾嗛挳 bodu PLA")
#define MSG_UBL_BUILD_ABS_MESH              _UxGT("S閾嗛挳 bodu ABS")
#define MSG_UBL_BUILD_COLD_MESH             _UxGT("Studen璋� s閾嗛挳 bod鏆�")
#define MSG_UBL_MESH_HEIGHT_ADJUST          _UxGT("Upravit v濯掓嫥ku s閾唗鑷�")
#define MSG_UBL_MESH_HEIGHT_AMOUNT          _UxGT("V濯掓嫥ka")
#define MSG_UBL_VALIDATE_MESH_MENU          _UxGT("Zkontrolovat s閾嗛挳")
#define MSG_UBL_VALIDATE_PLA_MESH           _UxGT("Kontrola s閾唗鑷� PLA")
#define MSG_UBL_VALIDATE_ABS_MESH           _UxGT("Kontrola s閾唗鑷� ABS")
#define MSG_UBL_VALIDATE_CUSTOM_MESH        _UxGT("Kontrola vlast. s閾唗鑷�")
#define MSG_UBL_CONTINUE_MESH               _UxGT("Pokra鑶穙vat v s閾嗛挳i")
#define MSG_UBL_MESH_LEVELING               _UxGT("S閾嗛挳ov鑼� rovn璋﹏閾�")
#define MSG_UBL_3POINT_MESH_LEVELING        _UxGT("3-bodove rovn璋﹏閾�")
#define MSG_UBL_GRID_MESH_LEVELING          _UxGT("Mrizkove rovn璋﹏閾�")
#define MSG_UBL_MESH_LEVEL                  _UxGT("Srovnat podlo鍟猭u")
#define MSG_UBL_SIDE_POINTS                 _UxGT("Postrann閾� body")
#define MSG_UBL_MAP_TYPE                    _UxGT("Typ s閾唗鑷� bodu")
#define MSG_UBL_OUTPUT_MAP                  _UxGT("Exportovat s閾嗛挳")
#define MSG_UBL_OUTPUT_MAP_HOST             _UxGT("Exportovat do PC")
#define MSG_UBL_OUTPUT_MAP_CSV              _UxGT("Exportovat do CSV")
#define MSG_UBL_OUTPUT_MAP_BACKUP           _UxGT("Z璋﹍oha do PC")
#define MSG_UBL_INFO_UBL                    _UxGT("Info o UBL do PC")
#define MSG_UBL_EDIT_MESH_MENU              _UxGT("Upravit s閾嗛挳 bod鏆�")
#define MSG_UBL_FILLIN_AMOUNT               _UxGT("Hustota m鑹￠搯鍟猭y")
#define MSG_UBL_MANUAL_FILLIN               _UxGT("Ru鑶穘閾� hustota")
#define MSG_UBL_SMART_FILLIN                _UxGT("Chytr璋� hustota")
#define MSG_UBL_FILLIN_MESH                 _UxGT("Zaplnit m鑹￠搯鍟猭u")
#define MSG_UBL_INVALIDATE_ALL              _UxGT("Zru鎷t v鎷chno")
#define MSG_UBL_INVALIDATE_CLOSEST          _UxGT("Zru鎷t posledn閾�")
#define MSG_UBL_FINE_TUNE_ALL               _UxGT("Upravit v鎷chny")
#define MSG_UBL_FINE_TUNE_CLOSEST           _UxGT("Upravit posledn閾�")
#define MSG_UBL_STORAGE_MESH_MENU           _UxGT("Ulo鍟猧鎷鑷� s閾唗閾�")
#define MSG_UBL_STORAGE_SLOT                _UxGT("Pam鑷庨挳ov濯� slot")
#define MSG_UBL_LOAD_MESH                   _UxGT("Na鑶烽搯st s閾嗛挳 bod鏆�")
#define MSG_UBL_SAVE_MESH                   _UxGT("Ulo鍟猧t s閾嗛挳 bod鏆�")
#define MSG_MESH_LOADED                     _UxGT("S閾嗛挳 %i na鑶穞ena")
#define MSG_MESH_SAVED                      _UxGT("S閾嗛挳 %i ulo鍟猠na")
#define MSG_NO_STORAGE                      _UxGT("Nedostatek m閾唖ta")
#define MSG_UBL_SAVE_ERROR                  _UxGT("Err: Ulo鍟猧t UBL")
#define MSG_UBL_RESTORE_ERROR               _UxGT("Err: Obnovit UBL")
#define MSG_UBL_Z_OFFSET_STOPPED            _UxGT("Konec Z-Offsetu")
#define MSG_UBL_STEP_BY_STEP_MENU           _UxGT("UBL Postupn鑷�")

#define MSG_LED_CONTROL                     _UxGT("LED Nastaven閾�")
#define MSG_LEDS_ON                         _UxGT("Sv鑷巘la Zap")
#define MSG_LEDS_OFF                        _UxGT("Sv鑷巘la Vyp")
#define MSG_LED_PRESETS                     _UxGT("Sv鑷巘la P鑹dvolby")
#define MSG_SET_LEDS_RED                    _UxGT("Sv鑷巘la 鑶秂rven璋�")
#define MSG_SET_LEDS_ORANGE                 _UxGT("Sv鑷巘la Oran鍟猳v璋�")
#define MSG_SET_LEDS_YELLOW                 _UxGT("Sv鑷巘la 娌ut璋�")
#define MSG_SET_LEDS_GREEN                  _UxGT("Sv鑷巘la Zelen璋�")
#define MSG_SET_LEDS_BLUE                   _UxGT("Sv鑷巘la Modr璋�")
#define MSG_SET_LEDS_INDIGO                 _UxGT("Sv鑷巘la Indigo")
#define MSG_SET_LEDS_VIOLET                 _UxGT("Sv鑷巘la Fialov璋�")
#define MSG_SET_LEDS_WHITE                  _UxGT("Sv鑷巘la B閾唋璋�")
#define MSG_SET_LEDS_DEFAULT                _UxGT("Sv鑷巘la V濯抍hoz閾�")
#define MSG_CUSTOM_LEDS                     _UxGT("Vlastn閾� sv鑷巘la")
#define MSG_INTENSITY_R                     _UxGT("鑶秂rven璋� intenzita")
#define MSG_INTENSITY_G                     _UxGT("Zelen璋� intezita")
#define MSG_INTENSITY_B                     _UxGT("Modr璋� intenzita")
#define MSG_INTENSITY_W                     _UxGT("B閾唋璋� intenzita")
#define MSG_LED_BRIGHTNESS                  _UxGT("Jas")

#define MSG_USER_MENU                       _UxGT("Vlastn閾� p鑹￠搯kazy")
#define MSG_MOVING                          _UxGT("Posouvani...")
#define MSG_FREE_XY                         _UxGT("Uvolnit XY")
#define MSG_MOVE_X                          _UxGT("Posunout X")
#define MSG_MOVE_Y                          _UxGT("Posunout Y")
#define MSG_MOVE_Z                          _UxGT("Posunout Z")
#define MSG_MOVE_E                          _UxGT("Extrud鑼卹")
#define MSG_MOVE_01MM                       _UxGT("Posunout o 0,1mm")
#define MSG_MOVE_1MM                        _UxGT("Posunout o 1mm")
#define MSG_MOVE_10MM                       _UxGT("Posunout o 10mm")
#define MSG_SPEED                           _UxGT("Rychlost")
#define MSG_BED_Z                           _UxGT("V濯掓嫥ka podl.")
#define MSG_NOZZLE                          _UxGT("Tryska")
#define MSG_BED                             _UxGT("Podlo鍟猭a")
#define MSG_FAN_SPEED                       _UxGT("Rychlost vent.")
#define MSG_EXTRA_FAN_SPEED                 _UxGT("Rychlost ex. vent.")
#define MSG_FLOW                            _UxGT("Pr鏆杢ok")
#define MSG_CONTROL                         _UxGT("Ovl璋ヾan閾�")
#define MSG_MIN                             _UxGT(" ") LCD_STR_THERMOMETER _UxGT(" Min")
#define MSG_MAX                             _UxGT(" ") LCD_STR_THERMOMETER _UxGT(" Max")
#define MSG_FACTOR                          _UxGT(" ") LCD_STR_THERMOMETER _UxGT(" Fakt")
#define MSG_AUTOTEMP                        _UxGT("Autoteplota")
#define MSG_ON                              _UxGT("Zap")
#define MSG_OFF                             _UxGT("Vyp")
#define MSG_PID_P                           _UxGT("PID-P")
#define MSG_PID_I                           _UxGT("PID-I")
#define MSG_PID_D                           _UxGT("PID-D")
#define MSG_PID_C                           _UxGT("PID-C")
#define MSG_SELECT                          _UxGT("Vybrat")
#define MSG_ACC                             _UxGT("Zrychl")
#define MSG_JERK                            _UxGT("Jerk")
#define MSG_VX_JERK                         _UxGT("Vx-jerk")
#define MSG_VY_JERK                         _UxGT("Vy-jerk")
#define MSG_VZ_JERK                         _UxGT("Vz-jerk")
#define MSG_VE_JERK                         _UxGT("Ve-jerk")
#define MSG_VELOCITY                        _UxGT("Rychlost")
#define MSG_VMAX                            _UxGT("Vmax ")
#define MSG_VMIN                            _UxGT("Vmin")
#define MSG_VTRAV_MIN                       _UxGT("VTrav min")
#define MSG_ACCELERATION                    _UxGT("Akcelerace")
#define MSG_AMAX                            _UxGT("Amax ")
#define MSG_A_RETRACT                       _UxGT("A-retrakt")
#define MSG_A_TRAVEL                        _UxGT("A-p鑹jezd")
#define MSG_STEPS_PER_MM                    _UxGT("Krok鏆�/mm")
#define MSG_XSTEPS                          _UxGT("Xkrok鏆�/mm")
#define MSG_YSTEPS                          _UxGT("Ykrok鏆�/mm")
#define MSG_ZSTEPS                          _UxGT("Zkrok鏆�/mm")
#define MSG_ESTEPS                          _UxGT("Ekrok鏆�/mm")
#define MSG_E1STEPS                         _UxGT("E1krok鏆�/mm")
#define MSG_E2STEPS                         _UxGT("E2krok鏆�/mm")
#define MSG_E3STEPS                         _UxGT("E3krok鏆�/mm")
#define MSG_E4STEPS                         _UxGT("E4krok鏆�/mm")
#define MSG_E5STEPS                         _UxGT("E5krok鏆�/mm")
#define MSG_TEMPERATURE                     _UxGT("Teplota")
#define MSG_MOTION                          _UxGT("Pohyb")
#define MSG_FILAMENT                        _UxGT("Filament")
#define MSG_VOLUMETRIC_ENABLED              _UxGT("E na mm3")
#define MSG_FILAMENT_DIAM                   _UxGT("Fil. Prum.")
#define MSG_ADVANCE_K                       _UxGT("K pro posun")
#define MSG_CONTRAST                        _UxGT("Kontrast LCD")
#define MSG_STORE_EEPROM                    _UxGT("Ulo鍟猧t nastaven閾�")
#define MSG_LOAD_EEPROM                     _UxGT("Na鑶烽搯st nastaven閾�")
#define MSG_RESTORE_FAILSAFE                _UxGT("Obnovit v濯抍hoz閾�")
#define MSG_INIT_EEPROM                     _UxGT("Inic. EEPROM")
#define MSG_REFRESH                         _UxGT("Obnovit")
#define MSG_WATCH                           _UxGT("Info obrazovka")
#define MSG_PREPARE                         _UxGT("P鑹prava tisku")
#define MSG_TUNE                            _UxGT("Dolad鑷巒閾� tisku")
#define MSG_PAUSE_PRINT                     _UxGT("Pozastavit tisk")
#define MSG_RESUME_PRINT                    _UxGT("Obnovit tisk")
#define MSG_STOP_PRINT                      _UxGT("Zastavit tisk")
#define MSG_CARD_MENU                       _UxGT("Tisknout z SD")
#define MSG_NO_CARD                         _UxGT("娌よ癌dn璋� SD karta")
#define MSG_DWELL                           _UxGT("Usp璋﹏o...")
#define MSG_USERWAIT                        _UxGT("鑶秂k璋﹏閾� na u鍟猧v...")
#define MSG_PRINT_PAUSED                    _UxGT("Tisk pozastaven")
#define MSG_RESUMING                        _UxGT("Obnovov璋﹏閾� tisku")
#define MSG_PRINT_ABORTED                   _UxGT("Tisk zru鎷n")
#define MSG_NO_MOVE                         _UxGT("娌よ癌dn濯� pohyb.")
#define MSG_KILLED                          _UxGT("P鑹燛RUSENO. ")
#define MSG_STOPPED                         _UxGT("ZASTAVENO. ")
#define MSG_CONTROL_RETRACT                 _UxGT("Retrakt mm")
#define MSG_CONTROL_RETRACT_SWAP            _UxGT("V濯抦鑷巒a Re.mm")
#define MSG_CONTROL_RETRACTF                _UxGT("Retraktovat  V")
#define MSG_CONTROL_RETRACT_ZLIFT           _UxGT("Zvednuti Z mm")
#define MSG_CONTROL_RETRACT_RECOVER         _UxGT("UnRet mm")
#define MSG_CONTROL_RETRACT_RECOVER_SWAP    _UxGT("S UnRet mm")
#define MSG_CONTROL_RETRACT_RECOVERF        _UxGT("UnRet  V")
#define MSG_CONTROL_RETRACT_RECOVER_SWAPF   _UxGT("S UnRet V")
#define MSG_AUTORETRACT                     _UxGT("AutoRetr.")
#define MSG_FILAMENTCHANGE                  _UxGT("Vym鑷巒it filament")
#define MSG_INIT_SDCARD                     _UxGT("Na鑶烽搯st SD kartu")
#define MSG_CNG_SDCARD                      _UxGT("Vym鑷巒it SD kartu")
#define MSG_ZPROBE_OUT                      _UxGT("Sonda Z mimo podl")
#define MSG_SKEW_FACTOR                     _UxGT("Faktor zkosen閾�")
#define MSG_BLTOUCH                         _UxGT("BLTouch")
#define MSG_BLTOUCH_SELFTEST                _UxGT("BLTouch Self-Test")
#define MSG_BLTOUCH_RESET                   _UxGT("BLTouch Reset")
#define MSG_BLTOUCH_DEPLOY                  _UxGT("BLTouch Vysunout")
#define MSG_BLTOUCH_STOW                    _UxGT("BLTouch Zasunout")
#define MSG_HOME                            _UxGT("Dom鏆�")  // Used as MSG_HOME " " MSG_X MSG_Y MSG_Z " " MSG_FIRST
#define MSG_FIRST                           _UxGT("prvn閾�")
#define MSG_ZPROBE_ZOFFSET                  _UxGT("Z ofset")
#define MSG_BABYSTEP_X                      _UxGT("Babystep X")
#define MSG_BABYSTEP_Y                      _UxGT("Babystep Y")
#define MSG_BABYSTEP_Z                      _UxGT("Babystep Z")
#define MSG_ENDSTOP_ABORT                   _UxGT("Endstop abort")
#define MSG_HEATING_FAILED_LCD              _UxGT("Chyba zah鑹￠搯v璋﹏閾�")
#define MSG_ERR_REDUNDANT_TEMP              _UxGT("REDUND. TEPLOTA")
#define MSG_THERMAL_RUNAWAY                 _UxGT("TEPLOTN鑴� SKOK")
#define MSG_ERR_MAXTEMP                     _UxGT("VYSOK鑴� TEPLOTA")
#define MSG_ERR_MINTEMP                     _UxGT("N鑴KA TEPLOTA")
#define MSG_ERR_MAXTEMP_BED                 _UxGT("VYS. TEPL. PODL.")
#define MSG_ERR_MINTEMP_BED                 _UxGT("N鑴. TEPL. PODL.")
#define MSG_ERR_Z_HOMING                    _UxGT("G28 Z ZAK鑴昛鑴昇O")
#define MSG_HALTED                          _UxGT("TISK. ZASTAVENA")
#define MSG_PLEASE_RESET                    _UxGT("Prove鑶箃e reset")
#define MSG_SHORT_DAY                       _UxGT("d")
#define MSG_SHORT_HOUR                      _UxGT("h")
#define MSG_SHORT_MINUTE                    _UxGT("m")
#define MSG_HEATING                         _UxGT("Zah鑹￠搯v璋﹏閾�...")
#define MSG_HEATING_COMPLETE                _UxGT("Zah鑹¤癌ti hotovo.")
#define MSG_BED_HEATING                     _UxGT("Zah鑹￠搯v璋﹏閾� podl.")
#define MSG_BED_DONE                        _UxGT("Podlo鍟猭a hotova.")
#define MSG_DELTA_CALIBRATE                 _UxGT("Delta Kalibrace")
#define MSG_DELTA_CALIBRATE_X               _UxGT("Kalibrovat X")
#define MSG_DELTA_CALIBRATE_Y               _UxGT("Kalibrovat Y")
#define MSG_DELTA_CALIBRATE_Z               _UxGT("Kalibrovat Z")
#define MSG_DELTA_CALIBRATE_CENTER          _UxGT("Kalibrovat St鑹d")
#define MSG_DELTA_SETTINGS                  _UxGT("Delta nastaven閾�")
#define MSG_DELTA_AUTO_CALIBRATE            _UxGT("Autokalibrace")
#define MSG_DELTA_HEIGHT_CALIBRATE          _UxGT("Nast.v濯掓嫥ku delty")
#define MSG_DELTA_DIAG_ROD                  _UxGT("Diag rameno")
#define MSG_DELTA_HEIGHT                    _UxGT("V濯掓嫥ka")
#define MSG_DELTA_RADIUS                    _UxGT("Polom鑷巖")
#define MSG_INFO_MENU                       _UxGT("O tisk璋﹔n鑷�")
#define MSG_INFO_PRINTER_MENU               _UxGT("Info o tisk璋﹔n鑷�")
#define MSG_3POINT_LEVELING                 _UxGT("3-bodov鑼� rovn璋﹏閾�")
#define MSG_LINEAR_LEVELING                 _UxGT("Line璋﹔ni rovn璋﹏閾�")
#define MSG_BILINEAR_LEVELING               _UxGT("Biline璋﹔n閾� rovn璋﹏閾�")
#define MSG_UBL_LEVELING                    _UxGT("Unified Bed Leveling")
#define MSG_MESH_LEVELING                   _UxGT("M鑹￠搯鍟猭ov鑼� rovn璋﹏閾�")
#define MSG_INFO_STATS_MENU                 _UxGT("Statistika")
#define MSG_INFO_BOARD_MENU                 _UxGT("Info o desce")
#define MSG_INFO_THERMISTOR_MENU            _UxGT("Termistory")
#define MSG_INFO_EXTRUDERS                  _UxGT("Extrud鑼卹y")
#define MSG_INFO_BAUDRATE                   _UxGT("Rychlost")
#define MSG_INFO_PROTOCOL                   _UxGT("Protokol")
#define MSG_CASE_LIGHT                      _UxGT("Osv鑷巘len閾�")
#define MSG_CASE_LIGHT_BRIGHTNESS           _UxGT("Jas sv鑷巘la")

#if LCD_WIDTH >= 20
  #define MSG_INFO_PRINT_COUNT              _UxGT("Po鑶積t tisk鏆�")
  #define MSG_INFO_COMPLETED_PRINTS         _UxGT("Dokon鑶積no")
  #define MSG_INFO_PRINT_TIME               _UxGT("Celkov濯� 鑶穉s")
  #define MSG_INFO_PRINT_LONGEST            _UxGT("Nejdel鎷ч搯 tisk")
  #define MSG_INFO_PRINT_FILAMENT           _UxGT("Celkem vytla鑶積no")
#else
  #define MSG_INFO_PRINT_COUNT              _UxGT("Tisky")
  #define MSG_INFO_COMPLETED_PRINTS         _UxGT("Hotovo")
  #define MSG_INFO_PRINT_TIME               _UxGT("鑶禷s")
  #define MSG_INFO_PRINT_LONGEST            _UxGT("Nejdel鎷ч搯")
  #define MSG_INFO_PRINT_FILAMENT           _UxGT("Vytla鑶積no")
#endif

#define MSG_INFO_MIN_TEMP                   _UxGT("Teplota min")
#define MSG_INFO_MAX_TEMP                   _UxGT("Teplota max")
#define MSG_INFO_PSU                        _UxGT("Nap. zdroj")
#define MSG_DRIVE_STRENGTH                  _UxGT("Buzen閾� motor鏆�")
#define MSG_DAC_PERCENT                     _UxGT("Motor %")
#define MSG_DAC_EEPROM_WRITE                _UxGT("Ulo鍟猧t do EEPROM")
#define MSG_FILAMENT_CHANGE_HEADER          _UxGT("PRINT PAUSED")
#define MSG_FILAMENT_CHANGE_OPTION_HEADER   _UxGT("RESUME OPTIONS:")
#define MSG_FILAMENT_CHANGE_OPTION_EXTRUDE  _UxGT("Je鎷鑷� vytla鑶穒t")
#define MSG_FILAMENT_CHANGE_OPTION_RESUME   _UxGT("Obnovit tisk")
#define MSG_FILAMENT_CHANGE_MINTEMP         _UxGT("Min. teplota je ")
#define MSG_FILAMENT_CHANGE_NOZZLE          _UxGT("  Tryska: ")
#define MSG_ERR_HOMING_FAILED               _UxGT("Parkov璋﹏閾� selhalo")
#define MSG_ERR_PROBING_FAILED              _UxGT("Kalibrace selhala")

#if LCD_HEIGHT >= 4
  // Up to 3 lines allowed
  #define MSG_FILAMENT_CHANGE_INIT_1          _UxGT("鑶秂kejte pros閾唌")
  #define MSG_FILAMENT_CHANGE_INIT_2          _UxGT("na zah璋﹋en閾�")
  #define MSG_FILAMENT_CHANGE_INIT_3          _UxGT("v濯抦鑷巒y filamentu")
  #define MSG_FILAMENT_CHANGE_UNLOAD_1        _UxGT("鑶秂kejte pros閾唌")
  #define MSG_FILAMENT_CHANGE_UNLOAD_2        _UxGT("na vysunuti")
  #define MSG_FILAMENT_CHANGE_UNLOAD_3        _UxGT("filamentu")
  #define MSG_FILAMENT_CHANGE_INSERT_1        _UxGT("Vlo鍟猼e filament")
  #define MSG_FILAMENT_CHANGE_INSERT_2        _UxGT("a stiskn鑷巘e")
  #define MSG_FILAMENT_CHANGE_INSERT_3        _UxGT("tla鑶烽搯tko...")
  #define MSG_FILAMENT_CHANGE_HEAT_1          _UxGT("Klikn鑷巘e pro")
  #define MSG_FILAMENT_CHANGE_HEAT_2          _UxGT("nah鑹¤癌t閾� trysky")
  #define MSG_FILAMENT_CHANGE_HEATING_1       _UxGT("鑶秂kejte pros閾唌")
  #define MSG_FILAMENT_CHANGE_HEATING_2       _UxGT("na nah鑹¤癌t閾� tr.")
  #define MSG_FILAMENT_CHANGE_LOAD_1          _UxGT("鑶秂kejte pros閾唌")
  #define MSG_FILAMENT_CHANGE_LOAD_2          _UxGT("na zaveden閾�")
  #define MSG_FILAMENT_CHANGE_LOAD_3          _UxGT("filamentu")
  #define MSG_FILAMENT_CHANGE_EXTRUDE_1       _UxGT("鑶秂kejte pros閾唌")
  #define MSG_FILAMENT_CHANGE_EXTRUDE_2       _UxGT("na vytla鑶積n閾�")
  #define MSG_FILAMENT_CHANGE_EXTRUDE_3       _UxGT("filamentu")
  #define MSG_FILAMENT_CHANGE_RESUME_1        _UxGT("鑶秂kejte pros閾唌")
  #define MSG_FILAMENT_CHANGE_RESUME_2        _UxGT("na pokra鑶穙v璋﹏閾�")
  #define MSG_FILAMENT_CHANGE_RESUME_3        _UxGT("tisku")
#else // LCD_HEIGHT < 4
  // Up to 2 lines allowed
  #define MSG_FILAMENT_CHANGE_INIT_1          _UxGT("鑶秂kejte...")
  #define MSG_FILAMENT_CHANGE_UNLOAD_1        _UxGT("Vysouv璋﹏閾�...")
  #define MSG_FILAMENT_CHANGE_INSERT_1        _UxGT("Vlo鍟猼e, klikn鑷巘e")
  #define MSG_FILAMENT_CHANGE_HEATING_1       _UxGT("Nah鑹￠搯v璋﹏閾�...")
  #define MSG_FILAMENT_CHANGE_LOAD_1          _UxGT("Zav璋ヾ鑷巒閾�...")
  #define MSG_FILAMENT_CHANGE_EXTRUDE_1       _UxGT("Vytla鑶穙v璋﹏閾�...")
  #define MSG_FILAMENT_CHANGE_RESUME_1        _UxGT("Pokra鑶穙v璋﹏閾�...")
#endif // LCD_HEIGHT < 4

#endif // LANGUAGE_CZ_UTF_H


