/**
 * Marlin 3D Printer Firmware
 * Copyright (C) 2016 MarlinFirmware [https://github.com/MarlinFirmware/Marlin]
 *
 * Based on Sprinter and grbl.
 * Copyright (C) 2011 Camiel Gubbels / Erik van der Zalm
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

/**
 * Slovak
 * UTF-8 for Graphical Display
 *
 * LCD Menu Messages
 * See also http://marlinfw.org/docs/development/lcd_language.html
 *
 * Translated by Michal Hole鎷�, Farma MaM
 * http://www.facebook.com/farmamam
 *
 */
#ifndef LANGUAGE_SK_UTF_H
#define LANGUAGE_SK_UTF_H

#define MAPPER_C3C4C5_SK
#define DISPLAY_CHARSET_ISO10646_SK

#define WELCOME_MSG                         MACHINE_NAME _UxGT(" pripraven璋�.")
#define MSG_BACK                            _UxGT("Naspa閽�")
#define MSG_SD_INSERTED                     _UxGT("Karta vlo鍟猠n璋�")
#define MSG_SD_REMOVED                      _UxGT("Karta vybrat璋�")
#define MSG_LCD_ENDSTOPS                    _UxGT("Endstopy") // max 8 znakov
#define MSG_MAIN                            _UxGT("Hlavn璋� ponuka")
#define MSG_AUTOSTART                       _UxGT("Auto鎷art")
#define MSG_DISABLE_STEPPERS                _UxGT("Uvolni閽� motory")
#define MSG_DEBUG_MENU                      _UxGT("Ponuka ladenia")
#define MSG_PROGRESS_BAR_TEST               _UxGT("Test uk. priebehu")
#define MSG_AUTO_HOME                       _UxGT("Domovsk璋� poz閾哻ia")
#define MSG_AUTO_HOME_X                     _UxGT("Domov os X")
#define MSG_AUTO_HOME_Y                     _UxGT("Domov os Y")
#define MSG_AUTO_HOME_Z                     _UxGT("Domov os Z")
#define MSG_LEVEL_BED_HOMING                _UxGT("Meranie podlo鍟猭y")
#define MSG_LEVEL_BED_WAITING               _UxGT("Kliknut閾唌 spus閽畉e")
#define MSG_LEVEL_BED_NEXT_POINT            _UxGT("鑶竌l鎷ч搯 bod")
#define MSG_LEVEL_BED_DONE                  _UxGT("Meranie hotov鑼�!")
#define MSG_Z_FADE_HEIGHT                   _UxGT("V濯掓嫥ka merania")
#define MSG_SET_HOME_OFFSETS                _UxGT("Nastavi閽� offsety")
#define MSG_HOME_OFFSETS_APPLIED            _UxGT("Offsety nastaven鑼�")
#define MSG_SET_ORIGIN                      _UxGT("Nastavi閽� za鑶穒atok")
#define MSG_PREHEAT_1                       _UxGT("Zahria閽� PLA")
#define MSG_PREHEAT_1_N                     MSG_PREHEAT_1 _UxGT(" ")
#define MSG_PREHEAT_1_ALL                   MSG_PREHEAT_1 _UxGT(" v鎷tko")
#define MSG_PREHEAT_1_END                   MSG_PREHEAT_1 _UxGT(" hotend")
#define MSG_PREHEAT_1_BEDONLY               MSG_PREHEAT_1 _UxGT(" podlo鍟�")
#define MSG_PREHEAT_1_SETTINGS              MSG_PREHEAT_1 _UxGT(" nast")
#define MSG_PREHEAT_2                       _UxGT("Zahria閽� ABS")
#define MSG_PREHEAT_2_N                     MSG_PREHEAT_2 _UxGT(" ")
#define MSG_PREHEAT_2_ALL                   MSG_PREHEAT_2 _UxGT(" v鎷tko")
#define MSG_PREHEAT_2_END                   MSG_PREHEAT_2 _UxGT(" hotend")
#define MSG_PREHEAT_2_BEDONLY               MSG_PREHEAT_2 _UxGT(" podlo鍟�")
#define MSG_PREHEAT_2_SETTINGS              MSG_PREHEAT_2 _UxGT(" nast")
#define MSG_COOLDOWN                        _UxGT("Schladi閽�")
#define MSG_SWITCH_PS_ON                    _UxGT("Zapn鐓ら挳 nap璋﹋anie")
#define MSG_SWITCH_PS_OFF                   _UxGT("Vypn鐓ら挳 nap璋﹋anie")
#define MSG_EXTRUDE                         _UxGT("Vytla鑶穒閽� (extr.)")
#define MSG_RETRACT                         _UxGT("Vytiahnu閽� (retr.)")
#define MSG_MOVE_AXIS                       _UxGT("Posun鐓ら挳 osy")
#define MSG_BED_LEVELING                    _UxGT("Vyrovna閽� podlo鍟猭u")
#define MSG_LEVEL_BED                       _UxGT("Vyrovna閽� podlo鍟猭u")
#define MSG_EDITING_STOPPED                 _UxGT("Koniec 鐓rav siete")

#define MSG_UBL_DOING_G29                   _UxGT("Vykon璋﹙am G29")
#define MSG_UBL_UNHOMED                     _UxGT("Prejdite domov")
#define MSG_UBL_TOOLS                       _UxGT("UBL n璋﹕troje")
#define MSG_UBL_LEVEL_BED                   _UxGT("Unified Bed Leveling")
#define MSG_UBL_MANUAL_MESH                 _UxGT("Manu璋﹍na sie閽� bodov")
#define MSG_UBL_BC_INSERT                   _UxGT("Vlo鍟猼e kartu, zmerajte")
#define MSG_UBL_BC_INSERT2                  _UxGT("Zmerajte")
#define MSG_UBL_BC_REMOVE                   _UxGT("Odstr璋╄墝te a zmerajte")
#define MSG_UBL_MOVING_TO_NEXT              _UxGT("Presun na 鑶筧l鎷ч搯")
#define MSG_UBL_ACTIVATE_MESH               _UxGT("Aktivova閽� UBL")
#define MSG_UBL_DEACTIVATE_MESH             _UxGT("Deaktivova閽� UBL")
#define MSG_UBL_SET_BED_TEMP                _UxGT("Teplota podlo鍟猭y")
#define MSG_UBL_CUSTOM_BED_TEMP             MSG_UBL_SET_BED_TEMP
#define MSG_UBL_SET_HOTEND_TEMP             _UxGT("Teplota hotendu")
#define MSG_UBL_CUSTOM_HOTEND_TEMP          MSG_UBL_SET_HOTEND_TEMP
#define MSG_UBL_EDIT_CUSTOM_MESH            _UxGT("Upravi閽� vlastn鐓� sie閽�")
#define MSG_UBL_FINE_TUNE_MESH              _UxGT("Doladi閽� sie閽� bodov")
#define MSG_UBL_DONE_EDITING_MESH           _UxGT("Koniec 鐓rav siete")
#define MSG_UBL_BUILD_CUSTOM_MESH           _UxGT("Vlastn璋� sie閽�")
#define MSG_UBL_BUILD_MESH_MENU             _UxGT("Vytvori閽� sie閽�")
#define MSG_UBL_BUILD_PLA_MESH              _UxGT("Sie閽� bodov PLA")
#define MSG_UBL_BUILD_ABS_MESH              _UxGT("Sie閽� bodov ABS")
#define MSG_UBL_BUILD_COLD_MESH             _UxGT("Studen璋� sie閽� bodov")
#define MSG_UBL_MESH_HEIGHT_ADJUST          _UxGT("Upravi閽� v濯掓嫥ku siete")
#define MSG_UBL_MESH_HEIGHT_AMOUNT          _UxGT("V濯掓嫥ka")
#define MSG_UBL_VALIDATE_MESH_MENU          _UxGT("Skontrolova閽� sie閽�")
#define MSG_UBL_VALIDATE_PLA_MESH           _UxGT("Kontrola siete PLA")
#define MSG_UBL_VALIDATE_ABS_MESH           _UxGT("Kontrola siete ABS")
#define MSG_UBL_VALIDATE_CUSTOM_MESH        _UxGT("Kontrola vlast. siete")
#define MSG_UBL_CONTINUE_MESH               _UxGT("Pokra鑶穙va閽� v sieti")
#define MSG_UBL_MESH_LEVELING               _UxGT("Sie閽畂v鑼� rovnanie")
#define MSG_UBL_3POINT_MESH_LEVELING        _UxGT("3-bodove rovnanie")
#define MSG_UBL_GRID_MESH_LEVELING          _UxGT("Mrie鍟猭ov鑼� rovnanie")
#define MSG_UBL_MESH_LEVEL                  _UxGT("Vyrovna閽� podlo鍟猭u")
#define MSG_UBL_SIDE_POINTS                 _UxGT("Postrann鑼� body")
#define MSG_UBL_MAP_TYPE                    _UxGT("Typ siete bodov")
#define MSG_UBL_OUTPUT_MAP                  _UxGT("Exportova閽� sie閽�")
#define MSG_UBL_OUTPUT_MAP_HOST             _UxGT("Exportova閽� do PC")
#define MSG_UBL_OUTPUT_MAP_CSV              _UxGT("Exportova閽� do CSV")
#define MSG_UBL_OUTPUT_MAP_BACKUP           _UxGT("Z璋﹍oha do PC")
#define MSG_UBL_INFO_UBL                    _UxGT("Info o UBL do PC")
#define MSG_UBL_EDIT_MESH_MENU              _UxGT("Upravi閽� sie閽� bodov")
#define MSG_UBL_FILLIN_AMOUNT               _UxGT("Hustota mrie鍟猭y")
#define MSG_UBL_MANUAL_FILLIN               _UxGT("Ru鑶穘璋� hustota")
#define MSG_UBL_SMART_FILLIN                _UxGT("Smart hustota")
#define MSG_UBL_FILLIN_MESH                 _UxGT("Zaplni閽� mrie鍟猭u")
#define MSG_UBL_INVALIDATE_ALL              _UxGT("Zru鎷閽� v鎷tko")
#define MSG_UBL_INVALIDATE_CLOSEST          _UxGT("Zru鎷閽� posledn濯�")
#define MSG_UBL_FINE_TUNE_ALL               _UxGT("Upravi閽� v鎷tky")
#define MSG_UBL_FINE_TUNE_CLOSEST           _UxGT("Upravi閽� posledn濯�")
#define MSG_UBL_STORAGE_MESH_MENU           _UxGT("Ulo鍟猧sko siet閾�")
#define MSG_UBL_STORAGE_SLOT                _UxGT("Pama閽畂v濯� slot")
#define MSG_UBL_LOAD_MESH                   _UxGT("Na鑶烽搯ta閽� sie閽� bodov")
#define MSG_UBL_SAVE_MESH                   _UxGT("Ulo鍟猧閽� sie閽� bodov")
#define MSG_UBL_SAVE_ERROR                  _UxGT("Err: Ulo鍟猧閽� UBL")
#define MSG_UBL_RESTORE_ERROR               _UxGT("Err: Obnovi閽� UBL")
#define MSG_UBL_Z_OFFSET_STOPPED            _UxGT("Koniec Z-Offsetu")
#define MSG_UBL_STEP_BY_STEP_MENU           _UxGT("UBL Postupne")

#define MSG_USER_MENU                       _UxGT("Vlastn鑼� pr閾唊azy")
#define MSG_MOVING                          _UxGT("Posun...")
#define MSG_FREE_XY                         _UxGT("Uvolni閽� XY")
#define MSG_MOVE_X                          _UxGT("Posun鐓ら挳 X")
#define MSG_MOVE_Y                          _UxGT("Posun鐓ら挳 Y")
#define MSG_MOVE_Z                          _UxGT("Posun鐓ら挳 Z")
#define MSG_MOVE_E                          _UxGT("Extr鐓er")
#define MSG_MOVE_01MM                       _UxGT("Posun鐓ら挳 o 0,1mm")
#define MSG_MOVE_1MM                        _UxGT("Posun鐓ら挳 o 1mm")
#define MSG_MOVE_10MM                       _UxGT("Posun鐓ら挳 o 10mm")
#define MSG_SPEED                           _UxGT("R濯抍hlos閽�")
#define MSG_BED_Z                           _UxGT("V濯掓嫥ka podl.")
#define MSG_NOZZLE                          _UxGT("Tryska")
#define MSG_BED                             _UxGT("Podlo鍟猭a")
#define MSG_FAN_SPEED                       _UxGT("R濯抍hlos閽� vent.")
#define MSG_FLOW                            _UxGT("Prietok")
#define MSG_CONTROL                         _UxGT("Ovl璋ヾanie")
#define MSG_MIN                             _UxGT(" ") LCD_STR_THERMOMETER _UxGT(" Min")
#define MSG_MAX                             _UxGT(" ") LCD_STR_THERMOMETER _UxGT(" Max")
#define MSG_FACTOR                          _UxGT(" ") LCD_STR_THERMOMETER _UxGT(" Fakt")
#define MSG_AUTOTEMP                        _UxGT("Autoteplota")
#define MSG_ON                              _UxGT("Zap")
#define MSG_OFF                             _UxGT("Vyp")
#define MSG_PID_P                           _UxGT("PID-P")
#define MSG_PID_I                           _UxGT("PID-I")
#define MSG_PID_D                           _UxGT("PID-D")
#define MSG_PID_C                           _UxGT("PID-C")
#define MSG_SELECT                          _UxGT("Vybra閽�")
#define MSG_ACC                             _UxGT("Zr濯抍hl")
#define MSG_JERK                            _UxGT("Skok")
#define MSG_VX_JERK                         _UxGT("Vx-skok")
#define MSG_VY_JERK                         _UxGT("Vy-skok")
#define MSG_VZ_JERK                         _UxGT("Vz-skok")
#define MSG_VE_JERK                         _UxGT("Ve-skok")
#define MSG_VELOCITY                        _UxGT("R濯抍hlos閽�")
#define MSG_VMAX                            _UxGT("Vmax ")
#define MSG_VMIN                            _UxGT("Vmin")
#define MSG_VTRAV_MIN                       _UxGT("VTrav min")
#define MSG_ACCELERATION                    _UxGT("Akceler璋ヽia")
#define MSG_AMAX                            _UxGT("Amax ")
#define MSG_A_RETRACT                       _UxGT("A-retrakt")
#define MSG_A_TRAVEL                        _UxGT("A-prejazd")
#define MSG_STEPS_PER_MM                    _UxGT("Krokov/mm")
#define MSG_XSTEPS                          _UxGT("Xkrokov/mm")
#define MSG_YSTEPS                          _UxGT("Ykrokov/mm")
#define MSG_ZSTEPS                          _UxGT("Zkrokov/mm")
#define MSG_ESTEPS                          _UxGT("Ekrokov/mm")
#define MSG_E1STEPS                         _UxGT("E1krokov/mm")
#define MSG_E2STEPS                         _UxGT("E2krokov/mm")
#define MSG_E3STEPS                         _UxGT("E3krokov/mm")
#define MSG_E4STEPS                         _UxGT("E4krokov/mm")
#define MSG_E5STEPS                         _UxGT("E5krok鏆�/mm")
#define MSG_TEMPERATURE                     _UxGT("Teplota")
#define MSG_MOTION                          _UxGT("Pohyb")
#define MSG_FILAMENT                        _UxGT("Filament")
#define MSG_VOLUMETRIC_ENABLED              _UxGT("E na mm3")
#define MSG_FILAMENT_DIAM                   _UxGT("Fil. Priem.")
#define MSG_ADVANCE_K                       _UxGT("K pro posun")
#define MSG_CONTRAST                        _UxGT("Kontrast LCD")
#define MSG_STORE_EEPROM                    _UxGT("Ulo鍟猧閽� nastavenie")
#define MSG_LOAD_EEPROM                     _UxGT("Na鑶烽搯ta閽� nastaven閾唀")
#define MSG_RESTORE_FAILSAFE                _UxGT("Obnovi閽� nastavenie")
#define MSG_INIT_EEPROM                     _UxGT("Inic. EEPROM")
#define MSG_REFRESH                         _UxGT("Obnovi閽�")
#define MSG_WATCH                           _UxGT("Info obrazovka")
#define MSG_PREPARE                         _UxGT("Pr閾唒rava tla鑶積")
#define MSG_TUNE                            _UxGT("Doladenie tla鑶積")
#define MSG_PAUSE_PRINT                     _UxGT("Pozastavi閽� tla鑶�")
#define MSG_RESUME_PRINT                    _UxGT("Obnovi閽� tla鑶�")
#define MSG_STOP_PRINT                      _UxGT("Zastavi閽� tla鑶�")
#define MSG_CARD_MENU                       _UxGT("Tla鑶穒閽� z SD")
#define MSG_NO_CARD                         _UxGT("娌adna SD karta")
#define MSG_DWELL                           _UxGT("Sp閾唌...")
#define MSG_USERWAIT                        _UxGT("鑶禷k璋﹎...")
#define MSG_PRINT_PAUSED                    _UxGT("Tla鑶� pozastaven璋�")
#define MSG_RESUMING                        _UxGT("Obnovovanie tla鑶積")
#define MSG_PRINT_ABORTED                   _UxGT("Tla鑶� zru鎷n璋�")
#define MSG_NO_MOVE                         _UxGT("娌adny pohyb.")
#define MSG_KILLED                          _UxGT("PRERU鑹〦N鑴�. ")
#define MSG_STOPPED                         _UxGT("ZASTAVEN鑴�. ")
#define MSG_CONTROL_RETRACT                 _UxGT("Retrakt mm")
#define MSG_CONTROL_RETRACT_SWAP            _UxGT("V濯抦ena Re.mm")
#define MSG_CONTROL_RETRACTF                _UxGT("Retraktova閽�  V")
#define MSG_CONTROL_RETRACT_ZLIFT           _UxGT("Zdvih Z mm")
#define MSG_CONTROL_RETRACT_RECOVER         _UxGT("UnRet mm")
#define MSG_CONTROL_RETRACT_RECOVER_SWAP    _UxGT("S UnRet mm")
#define MSG_CONTROL_RETRACT_RECOVERF        _UxGT("UnRet  V")
#define MSG_AUTORETRACT                     _UxGT("AutoRetr.")
#define MSG_FILAMENTCHANGE                  _UxGT("Vymeni閽� filament")
#define MSG_INIT_SDCARD                     _UxGT("Na鑶烽搯ta閽� SD kartu")
#define MSG_CNG_SDCARD                      _UxGT("Vymeni閽� SD kartu")
#define MSG_ZPROBE_OUT                      _UxGT("Sonda Z mimo podl")
#define MSG_BLTOUCH                         _UxGT("BLTouch")
#define MSG_BLTOUCH_SELFTEST                _UxGT("BLTouch Self-Test")
#define MSG_BLTOUCH_RESET                   _UxGT("BLTouch Reset")
#define MSG_BLTOUCH_DEPLOY                  _UxGT("BLTouch Vysun鐓ら挳")
#define MSG_BLTOUCH_STOW                    _UxGT("BLTouch Zasun鐓ら挳")
#define MSG_HOME                            _UxGT("Najprv")  // Used as MSG_HOME " " MSG_X MSG_Y MSG_Z " " MSG_FIRST
#define MSG_FIRST                           _UxGT("domov")
#define MSG_ZPROBE_ZOFFSET                  _UxGT("Z offset")
#define MSG_BABYSTEP_X                      _UxGT("Babystep X")
#define MSG_BABYSTEP_Y                      _UxGT("Babystep Y")
#define MSG_BABYSTEP_Z                      _UxGT("Babystep Z")
#define MSG_ENDSTOP_ABORT                   _UxGT("Endstop zastavil")
#define MSG_HEATING_FAILED_LCD              _UxGT("Chyba ohrevu")
#define MSG_ERR_REDUNDANT_TEMP              _UxGT("REDUND. TEPLOTA")
#define MSG_THERMAL_RUNAWAY                 _UxGT("TEPLOTN鑴� SKOK")
#define MSG_ERR_MAXTEMP                     _UxGT("VYSOK鑴� TEPLOTA")
#define MSG_ERR_MINTEMP                     _UxGT("N鑴KA TEPLOTA")
#define MSG_ERR_MAXTEMP_BED                 _UxGT("VYS. TEPL. PODL.")
#define MSG_ERR_MINTEMP_BED                 _UxGT("N鑴. TEPL. PODL.")
#define MSG_ERR_Z_HOMING                    _UxGT("G28 Z ZAK鑴昛AN鑴�")
#define MSG_HALTED                          _UxGT("TLA鑶�. ZASTAVEN鑴�")
#define MSG_PLEASE_RESET                    _UxGT("Spravte reset")
#define MSG_SHORT_DAY                       _UxGT("d")
#define MSG_SHORT_HOUR                      _UxGT("h")
#define MSG_SHORT_MINUTE                    _UxGT("m")
#define MSG_HEATING                         _UxGT("Ohrev...")
#define MSG_HEATING_COMPLETE                _UxGT("Ohrev prebehol.")
#define MSG_BED_HEATING                     _UxGT("Ohrev podl.")
#define MSG_BED_DONE                        _UxGT("Podlo鍟猭a hotov璋�.")
#define MSG_DELTA_CALIBRATE                 _UxGT("Delta Kalibr璋ヽia")
#define MSG_DELTA_CALIBRATE_X               _UxGT("Kalibrova閽� X")
#define MSG_DELTA_CALIBRATE_Y               _UxGT("Kalibrova閽� Y")
#define MSG_DELTA_CALIBRATE_Z               _UxGT("Kalibrova閽� Z")
#define MSG_DELTA_CALIBRATE_CENTER          _UxGT("Kalibrova閽� Stred")
#define MSG_DELTA_AUTO_CALIBRATE            _UxGT("Autokalibr璋ヽia")
#define MSG_DELTA_HEIGHT_CALIBRATE          _UxGT("Nast.v濯掓嫥ku delty")
#define MSG_INFO_MENU                       _UxGT("O tla鑶穒arni")
#define MSG_INFO_PRINTER_MENU               _UxGT("Info o tla鑶穒arni")
#define MSG_3POINT_LEVELING                 _UxGT("3-bodov鑼� rovnanie")
#define MSG_LINEAR_LEVELING                 _UxGT("Line璋﹔ne rovnanie")
#define MSG_BILINEAR_LEVELING               _UxGT("Biline璋﹔ne rovnanie")
#define MSG_UBL_LEVELING                    _UxGT("Unified Bed Leveling")
#define MSG_MESH_LEVELING                   _UxGT("Mrie鍟猭ov鑼� rovnanie")
#define MSG_INFO_STATS_MENU                 _UxGT("鑹﹖atistika")
#define MSG_INFO_BOARD_MENU                 _UxGT("Info o doske")
#define MSG_INFO_THERMISTOR_MENU            _UxGT("Termistory")
#define MSG_INFO_EXTRUDERS                  _UxGT("Extrud鑼卹y")
#define MSG_INFO_BAUDRATE                   _UxGT("R濯抍hlos閽�")
#define MSG_INFO_PROTOCOL                   _UxGT("Protokol")
#define MSG_CASE_LIGHT                      _UxGT("Osvetlenie")
#define MSG_CASE_LIGHT_BRIGHTNESS           _UxGT("Jas svetla")

#if LCD_WIDTH >= 20
  #define MSG_INFO_PRINT_COUNT              _UxGT("Po鑶積t tla鑶烽搯")
  #define MSG_INFO_COMPLETED_PRINTS         _UxGT("Dokon鑶積n鑼�")
  #define MSG_INFO_PRINT_TIME               _UxGT("Celkov濯� 鑶穉s")
  #define MSG_INFO_PRINT_LONGEST            _UxGT("Najdlh鎷a tla鑶�")
  #define MSG_INFO_PRINT_FILAMENT           _UxGT("Celkom vytla鑶積n鑼�")
#else
  #define MSG_INFO_PRINT_COUNT              _UxGT("Tla鑶積")
  #define MSG_INFO_COMPLETED_PRINTS         _UxGT("Hotovo")
  #define MSG_INFO_PRINT_TIME               _UxGT("鑶禷s")
  #define MSG_INFO_PRINT_LONGEST            _UxGT("Najdlh鎷a")
  #define MSG_INFO_PRINT_FILAMENT           _UxGT("Vytla鑶積n鑼�")
#endif

#define MSG_INFO_MIN_TEMP                   _UxGT("Teplota min")
#define MSG_INFO_MAX_TEMP                   _UxGT("Teplota max")
#define MSG_INFO_PSU                        _UxGT("Nap. zdroj")
#define MSG_DRIVE_STRENGTH                  _UxGT("Budenie motorov")
#define MSG_DAC_PERCENT                     _UxGT("Motor %")
#define MSG_DAC_EEPROM_WRITE                _UxGT("Ulo鍟猧閽� do EEPROM")

#define MSG_FILAMENT_CHANGE_HEADER          _UxGT("PAUZA TLA鑶禘")
#define MSG_FILAMENT_CHANGE_OPTION_HEADER   _UxGT("MO娌. POKRA鑶�.:")
#define MSG_FILAMENT_CHANGE_OPTION_EXTRUDE  _UxGT("E鎷e vytla鑶穒閽�")
#define MSG_FILAMENT_CHANGE_OPTION_RESUME   _UxGT("Obnovi閽� tla鑶�")
#define MSG_FILAMENT_CHANGE_MINTEMP         _UxGT("Min. teplota je ")
#define MSG_FILAMENT_CHANGE_NOZZLE          _UxGT("  Tryska: ")

#if LCD_HEIGHT >= 4
  // Up to 3 lines allowed
  #define MSG_FILAMENT_CHANGE_INIT_1          _UxGT("鑶禷kajte pros閾唌")
  #define MSG_FILAMENT_CHANGE_INIT_2          _UxGT("na spustenie")
  #define MSG_FILAMENT_CHANGE_INIT_3          _UxGT("v濯抦eny filamentu")
  #define MSG_FILAMENT_CHANGE_UNLOAD_1        _UxGT("鑶禷kejte pros閾唌")
  #define MSG_FILAMENT_CHANGE_UNLOAD_2        _UxGT("na vysunutie")
  #define MSG_FILAMENT_CHANGE_UNLOAD_3        _UxGT("filamentu")
  #define MSG_FILAMENT_CHANGE_INSERT_1        _UxGT("Vlo鍟猼e filament")
  #define MSG_FILAMENT_CHANGE_INSERT_2        _UxGT("a stla鑶穞e")
  #define MSG_FILAMENT_CHANGE_INSERT_3        _UxGT("tla鑶穒dlo...")
  #define MSG_FILAMENT_CHANGE_HEAT_1          _UxGT("Kliknite pre")
  #define MSG_FILAMENT_CHANGE_HEAT_2          _UxGT("ohrev trysky")
  #define MSG_FILAMENT_CHANGE_HEATING_1       _UxGT("鑶禷kajte pros閾唌")
  #define MSG_FILAMENT_CHANGE_HEATING_2       _UxGT("na teplotu tr.")
  #define MSG_FILAMENT_CHANGE_LOAD_1          _UxGT("鑶禷kajte pros閾唌")
  #define MSG_FILAMENT_CHANGE_LOAD_2          _UxGT("na zavedenie")
  #define MSG_FILAMENT_CHANGE_LOAD_3          _UxGT("filamentu")
  #define MSG_FILAMENT_CHANGE_EXTRUDE_1       _UxGT("鑶禷kajte pros閾唌")
  #define MSG_FILAMENT_CHANGE_EXTRUDE_2       _UxGT("na vytla鑶積nie")
  #define MSG_FILAMENT_CHANGE_EXTRUDE_3       _UxGT("filamentu")
  #define MSG_FILAMENT_CHANGE_RESUME_1        _UxGT("鑶禷kajte pros閾唌")
  #define MSG_FILAMENT_CHANGE_RESUME_2        _UxGT("na pokra鑶穙vanie")
  #define MSG_FILAMENT_CHANGE_RESUME_3        _UxGT("tla鑶積")
#else // LCD_HEIGHT < 4
  // Up to 2 lines allowed
  #define MSG_FILAMENT_CHANGE_INIT_1          _UxGT("鑶禷kajte...")
  #define MSG_FILAMENT_CHANGE_UNLOAD_1        _UxGT("Vys鐓anie...")
  #define MSG_FILAMENT_CHANGE_INSERT_1        _UxGT("Vlo鍟猼e, kliknite")
  #define MSG_FILAMENT_CHANGE_HEATING_1       _UxGT("Ohrev...")
  #define MSG_FILAMENT_CHANGE_LOAD_1          _UxGT("Zav璋ヾzanie...")
  #define MSG_FILAMENT_CHANGE_EXTRUDE_1       _UxGT("Vytla鑶穙vanie...")
  #define MSG_FILAMENT_CHANGE_RESUME_1        _UxGT("Pokra鑶穙vanie...")
#endif // LCD_HEIGHT < 4

#endif // LANGUAGE_SK_UTF_H


