/**
 * Marlin 3D Printer Firmware
 * Copyright (C) 2016 MarlinFirmware [https://github.com/MarlinFirmware/Marlin]
 *
 * Based on Sprinter and grbl.
 * Copyright (C) 2011 Camiel Gubbels / Erik van der Zalm
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

/**
 * Russian
 *
 * LCD Menu Messages
 * See also http://marlinfw.org/docs/development/lcd_language.html
 *
 */
#ifndef LANGUAGE_RU_H
#define LANGUAGE_RU_H

#define MAPPER_D0D1                // For Cyrillic
#define DISPLAY_CHARSET_ISO10646_5

#define WELCOME_MSG                         MACHINE_NAME _UxGT(" 琚氳姱瑜岃姱鑳�.")
#define MSG_BACK                            _UxGT("琚ч偑锜归偑鍐�")
#define MSG_SD_INSERTED                     _UxGT("琚ｉ偑瑜夎閭� 鑳佽瑜岄偑鑳佽阿姊拌柂閭�")
#define MSG_SD_REMOVED                      _UxGT("琚ｉ偑瑜夎閭� 鎳堣煿鑳佽阿姊拌姊拌柂閭�")
#define MSG_LCD_ENDSTOPS                    _UxGT("琚ｈ姱钖姊拌儊鎳堟郴鎳�")
#define MSG_MAIN                            _UxGT("琚︽钖")
#define MSG_AUTOSTART                       _UxGT("琚楄儊瑜岃姱瑜嬭閭瑜�")
#define MSG_DISABLE_STEPPERS                _UxGT("琚欒娉昏阿. 鍐欒儊鎳堣皭閭姊拌阿鎳�")
#define MSG_DEBUG_MENU                      _UxGT("琚︽钖 鑺璋㈤偑鍐欐郴鎳�")
#define MSG_PROGRESS_BAR_TEST               _UxGT("瀛濇瑜嬭 鎳堣柂鍐欐噲娉婚偑瑜岃姱瑜夐偑")
#define MSG_AUTO_HOME                       _UxGT("琚楄儊瑜岃姱 琚╅偑瑜夋郴鑺儊娉婚偑")
#define MSG_AUTO_HOME_X                     _UxGT("琚╅偑瑜夋郴鑺儊娉婚偑 X")
#define MSG_AUTO_HOME_Y                     _UxGT("琚╅偑瑜夋郴鑺儊娉婚偑 Y")
#define MSG_AUTO_HOME_Z                     _UxGT("琚╅偑瑜夋郴鑺儊娉婚偑 Z")
#define MSG_LEVEL_BED_HOMING                _UxGT("琚ц璋㈡鑳佽姱姊� 閿岃姱璋㈣姱鍗�")
#define MSG_LEVEL_BED_WAITING               _UxGT("琚ч偑鍗稿睉鎳堣姊� 钖偑瑜旈偑瑜岃")
#define MSG_LEVEL_BED_NEXT_POINT            _UxGT("灏忚阿姊板啓瑜嶈瑜栭偑瑜� 瑜岃姱瑜旀郴閭�")
#define MSG_LEVEL_BED_DONE                  _UxGT("琚欒瑜夐偑鑳佽柂鎳堣柂鑳侀偑鎳堟 璋愯姱瑜岃姱鑳佽姱!")
#define MSG_Z_FADE_HEIGHT                   _UxGT("琚欒瑜嬭姱瑜岄偑 瑜嬮攲閭啓閭�")
#define MSG_SET_HOME_OFFSETS                _UxGT("琚熼偑閿岃姱灞戣柂鎳堣瑜� 閿岄偑瑜夋郴鑺儊娉昏")
#define MSG_HOME_OFFSETS_APPLIED            _UxGT("琚ｈ姱瑜夎姊版郴瑜戞噲鎳� 閿岃鎳堝睉姊拌柂")
#define MSG_SET_ORIGIN                      _UxGT("琚熼偑閿岃姱灞戣柂鎳堣瑜� 钖姱璋㈣")
#define MSG_PREHEAT_1                       _UxGT("琚╄姊板啓钖偑璋愯姊拌儊 PLA")
#define MSG_PREHEAT_1_N                     MSG_PREHEAT_1 _UxGT(" ")
#define MSG_PREHEAT_1_ALL                   MSG_PREHEAT_1 _UxGT(" 琚欒瑜�")
#define MSG_PREHEAT_1_END                   MSG_PREHEAT_1 _UxGT(" 灏忚姱閿岃阿鑺�")
#define MSG_PREHEAT_1_BEDONLY               MSG_PREHEAT_1 _UxGT(" 灏忚鑺阿")
#define MSG_PREHEAT_1_SETTINGS              MSG_PREHEAT_1 _UxGT(" 琚ч偑瑜嬭瑜�.")
#define MSG_PREHEAT_2                       _UxGT("琚╄姊板啓钖偑璋愯姊拌儊 ABS")
#define MSG_PREHEAT_2_N                     MSG_PREHEAT_2 _UxGT(" ")
#define MSG_PREHEAT_2_ALL                   MSG_PREHEAT_2 _UxGT(" 琚欒瑜�")
#define MSG_PREHEAT_2_END                   MSG_PREHEAT_2 _UxGT(" 灏忚姱閿岃阿鑺�")
#define MSG_PREHEAT_2_BEDONLY               MSG_PREHEAT_2 _UxGT(" 灏忚鑺阿")
#define MSG_PREHEAT_2_SETTINGS              MSG_PREHEAT_2 _UxGT(" 琚ч偑瑜嬭瑜�.")
#define MSG_COOLDOWN                        _UxGT("琚ㄨ璋㈤偑鍗稿啓姊拌柂鎳堟")
#define MSG_SWITCH_PS_ON                    _UxGT("琚欐郴璋㈣瑜旀噲瑜岃 琚╂噲瑜岄偑钖噲姊�")
#define MSG_SWITCH_PS_OFF                   _UxGT("琚ㄨ娉昏阿瑜炶鎳堣瑜� 琚╂噲瑜岄偑钖噲姊�")
#define MSG_EXTRUDE                         _UxGT("鍗忔郴瑜嬭瑜夎锜规噲瑜�")
#define MSG_RETRACT                         _UxGT("琚欒瑜熻皭鎳堣儊閭柂鎳堟")
#define MSG_MOVE_AXIS                       _UxGT("琚涜儊鎳堝嵏姊拌柂鎳堟 閿岃姱 鑺瑜熷睉")
#define MSG_BED_LEVELING                    _UxGT("琚ｉ偑璋㈡噲鏂滆鑺儊閭瑜� 瑜嬭鑺阿")
#define MSG_LEVEL_BED                       _UxGT("琚ｉ偑璋㈡噲鏂滆鑺儊閭瑜� 瑜嬭鑺阿")
#define MSG_EDITING_STOPPED                 _UxGT("琚鍐�. 瑜嬫瑜屾郴鎳� 锜归偑鑳佹瑜夎姊拌柂閭�")
#define MSG_USER_MENU                       _UxGT("灏忚儊鑺噲 娉昏姱灞戝睉閭柂鍐欒")
#define MSG_UBL_DOING_G29                   _UxGT("琚欒閿岃姱璋㈣柂瑜熸灞� G29")
#define MSG_UBL_UNHOMED                     _UxGT("琚╅偑瑜夋郴瑜嶆灞� 瑜嬭柂閭閭阿閭� XYZ")
#define MSG_UBL_TOOLS                       _UxGT("鏍¤鎳堣阿鎳堣瑜� UBL")
#define MSG_UBL_LEVEL_BED                   _UxGT("琚ｉ偑璋㈡噲鏂滆鑺儊娉婚偑 UBL")
#define MSG_UBL_MANUAL_MESH                 _UxGT("琚╄姱瑜嬭瑜�. 瑜嬫瑜屾郴瑜� 鑺 瑜夎娉绘噲")
#define MSG_UBL_BC_INSERT                   _UxGT("琚╄姱瑜嬭. 瑜曟噲灞戝睉 鎳� 鎳堣煿灞戞瑜�.")
#define MSG_UBL_BC_INSERT2                  _UxGT("琚犺煿灞戞瑜夋钖噲姊�")
#define MSG_UBL_BC_REMOVE                   _UxGT("鏍″啓閭阿. 鎳� 鎳堣煿灞戞瑜�. 瑜嬭鑺阿")
#define MSG_UBL_MOVING_TO_NEXT              _UxGT("琚涜儊鎳堣皭閭灞戣瑜� 鍐欓偑璋㈣瑜曟")
#define MSG_UBL_ACTIVATE_MESH               _UxGT("琚楁郴瑜屾噲鑳佹噲瑜夎姱鑳侀偑瑜岃 UBL")
#define MSG_UBL_DEACTIVATE_MESH             _UxGT("琚欒娉昏阿瑜炶鎳堣瑜� UBL")
#define MSG_UBL_SET_BED_TEMP                _UxGT("瀛濇灞戦攲姊拌閭瑜嶈閭� 瑜嬭鑺阿閭�")
#define MSG_UBL_CUSTOM_BED_TEMP             MSG_UBL_SET_BED_TEMP
#define MSG_UBL_SET_HOTEND_TEMP             _UxGT("瀛濇灞戦攲姊拌閭瑜嶈閭� 瑜嬭姱閿岃阿閭�")
#define MSG_UBL_CUSTOM_HOTEND_TEMP          MSG_UBL_SET_HOTEND_TEMP
#define MSG_UBL_MESH_EDIT                   _UxGT("琚鍐欓偑娉昏鑺 瑜嬫瑜岃姱娉�")
#define MSG_UBL_EDIT_CUSTOM_MESH            _UxGT("琚鍐欓偑娉昏. 瑜嬭儊鑺 瑜嬫瑜屾郴瑜�")
#define MSG_UBL_FINE_TUNE_MESH              _UxGT("瀛濊姱瑜�. 钖偑瑜嬭瑜夎姱娉勬郴閭� 瑜嬫瑜屾郴鎳�")
#define MSG_UBL_DONE_EDITING_MESH           _UxGT("琚鍐�. 瑜嬫瑜屾郴鎳� 锜归偑鑳佹瑜夎姊拌柂鑺�")
#define MSG_UBL_BUILD_CUSTOM_MESH           _UxGT("琚╄姱瑜嬭瑜夎姱鎳堣瑜� 瑜嬭儊鑺 瑜嬫瑜屾郴瑜�")
#define MSG_UBL_BUILD_MESH_MENU             _UxGT("琚╄姱瑜嬭瑜夎姱鎳堣瑜� 瑜嬫瑜屾郴瑜�")
#define MSG_UBL_BUILD_PLA_MESH              _UxGT("琚╄姱瑜嬭瑜夎姱鎳堣瑜� 瑜嬫瑜屾郴瑜� PLA")
#define MSG_UBL_BUILD_ABS_MESH              _UxGT("琚╄姱瑜嬭瑜夎姱鎳堣瑜� 瑜嬫瑜屾郴瑜� ABS")
#define MSG_UBL_BUILD_COLD_MESH             _UxGT("琚╄姱瑜嬭瑜夎姱鎳堣瑜� 瑜忚姱璋�. 瑜嬫瑜屾郴瑜�")
#define MSG_UBL_MESH_HEIGHT_ADJUST          _UxGT("鏍¤瑜岄偑钖�. 鑳佽瑜嬭姱瑜岃 瑜嬫瑜屾郴鎳�")
#define MSG_UBL_MESH_HEIGHT_AMOUNT          _UxGT("琚欒瑜嬭姱瑜岄偑")
#define MSG_UBL_VALIDATE_MESH_MENU          _UxGT("琚╄鑺儊姊拌鎳堣瑜� 瑜嬫瑜屾郴瑜�")
#define MSG_UBL_VALIDATE_PLA_MESH           _UxGT("琚╄鑺儊姊拌鎳堣瑜� 瑜嬫瑜屾郴瑜� PLA")
#define MSG_UBL_VALIDATE_ABS_MESH           _UxGT("琚╄鑺儊姊拌鎳堣瑜� 瑜嬫瑜屾郴瑜� ABS")
#define MSG_UBL_VALIDATE_CUSTOM_MESH        _UxGT("琚╄鑺儊姊拌鎳堣瑜� 瑜嬭儊鑺 瑜嬫瑜屾郴瑜�")
#define MSG_UBL_CONTINUE_MESH               _UxGT("琚╄鑺啓鑺阿鍗告噲瑜岃 瑜嬫瑜屾郴瑜�")
#define MSG_UBL_MESH_LEVELING               _UxGT("琚ｉ偑璋㈡噲鏂滆鑺儊娉婚偑 瑜嬫瑜屾郴鎳�")
#define MSG_UBL_3POINT_MESH_LEVELING        _UxGT("琚ｉ偑璋㈡噲鏂滆鑺儊娉婚偑 3-瑜� 瑜岃姱瑜旀娉�")
#define MSG_UBL_GRID_MESH_LEVELING          _UxGT("琚ｉ偑璋㈡噲鏂滆鑺儊娉婚偑 瑜夐偑瑜嬭姊拌閭�")
#define MSG_UBL_MESH_LEVEL                  _UxGT("琚欒瑜夎姱鑳佽柂鎳堣瑜� 瑜嬫瑜屾郴瑜�")
#define MSG_UBL_SIDE_POINTS                 _UxGT("琚ｈ閭硠钖噲姊� 瑜岃姱瑜旀郴鎳�")
#define MSG_UBL_MAP_TYPE                    _UxGT("瀛濇噲閿� 娉婚偑瑜夎瑜�")
#define MSG_UBL_OUTPUT_MAP                  _UxGT("琚欒鑳佹瑜嬭鎳� 娉婚偑瑜夎瑜� 瑜嬫瑜屾郴鎳�")
#define MSG_UBL_OUTPUT_MAP_HOST             _UxGT("琚欒鑳佹瑜嬭鎳� 钖偑 瑜忚姱瑜嬭")
#define MSG_UBL_OUTPUT_MAP_CSV              _UxGT("琚欒鑳佹瑜嬭鎳� 鑳� CSV")
#define MSG_UBL_OUTPUT_MAP_BACKUP           _UxGT("琚熼偑鏂滄娉婚偑閿屾噲瑜岃 瑜嬫瑜屾郴瑜�")
#define MSG_UBL_INFO_UBL                    _UxGT("琚欒鍐欓偑瑜旈偑 鎳堣柂瑜庤姱瑜�. UBL")
#define MSG_UBL_EDIT_MESH_MENU              _UxGT("琚鍐欓偑娉昏鎳堣鑺儊閭瑜� 瑜嬫瑜屾郴瑜�")
#define MSG_UBL_FILLIN_AMOUNT               _UxGT("琚熼偑閿岃姱璋㈣柂鎳堣瑜� 锜硅柂閭姊拌柂鎳堣")
#define MSG_UBL_MANUAL_FILLIN               _UxGT("琚瑜旇柂鑺 锜归偑閿岃姱璋㈣柂姊拌柂鎳堟")
#define MSG_UBL_SMART_FILLIN                _UxGT("鏍″睉姊拌柂鑺 锜归偑閿岃姱璋㈣柂姊拌柂鎳堟")
#define MSG_UBL_FILLIN_MESH                 _UxGT("琚熼偑閿岃姱璋㈣柂鎳堣瑜� 瑜嬫瑜屾郴瑜�")
#define MSG_UBL_INVALIDATE_ALL              _UxGT("琚楄柂钖璋㈡噲瑜夎姱鑳侀偑瑜岃 鑳佽瑜�")
#define MSG_UBL_INVALIDATE_CLOSEST          _UxGT("琚楄柂钖璋㈡噲瑜�. 鏂滆阿鎳堝嵏. 瑜岃姱瑜旀郴瑜�")
#define MSG_UBL_FINE_TUNE_ALL               _UxGT("瀛濊姱瑜�. 钖偑瑜嬭瑜夎姱娉勬郴閭� 鑳佽姊拌皭鑺�")
#define MSG_UBL_FINE_TUNE_CLOSEST           _UxGT("琚ч偑瑜嬭瑜�. 鏂滆阿鎳堝嵏. 瑜岃姱瑜旀郴鎳�")
#define MSG_UBL_STORAGE_MESH_MENU           _UxGT("鍟歌閭柂鎳堣阿鎳堣姊� 瑜嬫瑜屾娉�")
#define MSG_UBL_STORAGE_SLOT                _UxGT("灏忚阿鑺 閿岄偑灞戣瑜屾噲")
#define MSG_UBL_LOAD_MESH                   _UxGT("琚熼偑璋愯瑜嶈煿鎳堣瑜� 瑜嬭鑺阿 瑜嬫瑜屾郴鎳�")
#define MSG_UBL_SAVE_MESH                   _UxGT("灏忚姱瑜忚閭柂鎳堣瑜� 瑜嬭鑺阿 瑜嬫瑜屾郴鎳�")
#define MSG_UBL_SAVE_ERROR                  _UxGT("琚ㄨ鎳堟枩娉婚偑: 灏忚姱瑜忚. UBL")
#define MSG_UBL_RESTORE_ERROR               _UxGT("琚ㄨ鎳堟枩娉婚偑: 琚熼偑璋愯瑜嶈煿娉绘噲 UBL")
#define MSG_UBL_Z_OFFSET_STOPPED            _UxGT("灏忓睉姊拌姊拌柂鎳堟 Z 鑺瑜岄偑钖姱鑳�.")
#define MSG_UBL_STEP_BY_STEP_MENU           _UxGT("琚╄姱瑜曢偑璋愯姱鑳佽娉� UBL")
#define MSG_MOVING                          _UxGT("琚涜儊鎳堝嵏姊板睉瑜嬭...")
#define MSG_FREE_XY                         _UxGT("琚ㄨ鑳佽姱鏂滆姱鍗稿啓閭灞� XY")
#define MSG_MOVE_X                          _UxGT("琚涜儊鎳堝嵏姊拌柂鎳堟 閿岃姱 X")
#define MSG_MOVE_Y                          _UxGT("琚涜儊鎳堝嵏姊拌柂鎳堟 閿岃姱 Y")
#define MSG_MOVE_Z                          _UxGT("琚涜儊鎳堝嵏姊拌柂鎳堟 閿岃姱 Z")
#define MSG_MOVE_E                          _UxGT("鍗忔郴瑜嬭瑜夎鍐欐瑜�")
#define MSG_MOVE_01MM                       _UxGT("琚涜儊鎳堝嵏姊拌柂鎳堟 0.1mm")
#define MSG_MOVE_1MM                        _UxGT("琚涜儊鎳堝嵏姊拌柂鎳堟 1mm")
#define MSG_MOVE_10MM                       _UxGT("琚涜儊鎳堝嵏姊拌柂鎳堟 10mm")
#define MSG_SPEED                           _UxGT("灏忔郴鑺鑺瑜岃")
#define MSG_BED_Z                           _UxGT("Z 瑜嬭鑺阿閭�")
#define MSG_NOZZLE                          LCD_STR_THERMOMETER _UxGT(" 灏忚姱閿岃阿鑺�")
#define MSG_BED                             LCD_STR_THERMOMETER _UxGT(" 灏忚鑺阿")
#define MSG_FAN_SPEED                       _UxGT("琚ｈ璋㈡瑜�")
#define MSG_FLOW                            _UxGT("琚╄姱瑜岃姱娉�")
#define MSG_CONTROL                         _UxGT("琚ч偑瑜嬭瑜夎姱娉勬郴鎳�")
#define MSG_MIN                             LCD_STR_THERMOMETER _UxGT(" 琚︽噲钖噲灞戣灞�")
#define MSG_MAX                             LCD_STR_THERMOMETER _UxGT(" 琚﹂偑娉昏鎳堝睉瑜嶅睉")
#define MSG_FACTOR                          LCD_STR_THERMOMETER _UxGT(" 鑲栭偑娉昏鑺")
#define MSG_AUTOTEMP                        _UxGT("琚楄儊瑜岃姱瑜屾灞戦攲姊拌閭瑜嶈閭�")
#define MSG_ON                              _UxGT("琚欐郴璋�. ")
#define MSG_OFF                             _UxGT("琚ㄨ娉昏阿. ")
#define MSG_PID_P                           _UxGT("PID-P")
#define MSG_PID_I                           _UxGT("PID-I")
#define MSG_PID_D                           _UxGT("PID-D")
#define MSG_PID_C                           _UxGT("PID-C")
#define MSG_SELECT                          _UxGT("琚欒鏂滆姱瑜�")
#define MSG_ACC                             _UxGT("鏍¤娉昏姱瑜夋钖噲姊�")
#define MSG_JERK                            _UxGT("琚鑳佽姱娉�")
#define MSG_VX_JERK                         _UxGT("Vx-瑜夎鑳佽姱娉�")
#define MSG_VY_JERK                         _UxGT("Vy-瑜夎鑳佽姱娉�")
#define MSG_VZ_JERK                         _UxGT("Vz-瑜夎鑳佽姱娉�")
#define MSG_VE_JERK                         _UxGT("Ve-瑜夎鑳佽姱娉�")
#define MSG_VELOCITY                        _UxGT("灏忔郴鑺鑺瑜岃")
#define MSG_VMAX                            _UxGT("V灞戦偑娉昏 ")
#define MSG_VMIN                            _UxGT("V灞戞噲钖�")
#define MSG_VTRAV_MIN                       _UxGT("V閿岃瑜屾瑜�. 灞戞噲钖�")
#define MSG_ACCELERATION                    _UxGT("鏍¤娉昏姱瑜夋钖噲姊�")
#define MSG_AMAX                            _UxGT("A灞戦偑娉昏")
#define MSG_A_RETRACT                       _UxGT("A-鑳佽瑜熻皭鎳堣儊閭柂鎳堟")
#define MSG_A_TRAVEL                        _UxGT("A-閿岃瑜屾瑜�.")
#define MSG_STEPS_PER_MM                    _UxGT("妤旈偑璋�/灞戝睉")
#define MSG_XSTEPS                          _UxGT("X 瑜曢偑璋�/灞戝睉")
#define MSG_YSTEPS                          _UxGT("Y 瑜曢偑璋�/灞戝睉")
#define MSG_ZSTEPS                          _UxGT("Z 瑜曢偑璋�/灞戝睉")
#define MSG_ESTEPS                          _UxGT("E 瑜曢偑璋�/灞戝睉")
#define MSG_E1STEPS                         _UxGT("E1 瑜曢偑璋�/灞戝睉")
#define MSG_E2STEPS                         _UxGT("E2 瑜曢偑璋�/灞戝睉")
#define MSG_E3STEPS                         _UxGT("E3 瑜曢偑璋�/灞戝睉")
#define MSG_E4STEPS                         _UxGT("E4 瑜曢偑璋�/灞戝睉")
#define MSG_E5STEPS                         _UxGT("E5 瑜曢偑璋�/灞戝睉")
#define MSG_TEMPERATURE                     _UxGT("瀛濇灞戦攲姊拌閭瑜嶈閭�")
#define MSG_MOTION                          _UxGT("琚︽瑜忛偑钖噲娉婚偑")
#define MSG_FILAMENT                        _UxGT("琚╄瑜嶈鑺郴")
#define MSG_VOLUMETRIC_ENABLED              _UxGT("E 鑳� mm3")
#define MSG_FILAMENT_DIAM                   _UxGT("琚涙噲閭睉姊拌瑜� 閿岃瑜嶈娉婚偑")
#define MSG_ADVANCE_K                       _UxGT("K 閿岃鑺啓鑳佹噲鍗告钖噲瑜�")
#define MSG_CONTRAST                        _UxGT("琚ｈ姱钖瑜夐偑瑜嬭 LCD")
#define MSG_STORE_EEPROM                    _UxGT("灏忚姱瑜忚閭柂鎳堣瑜� 鑳� EEPROM")
#define MSG_LOAD_EEPROM                     _UxGT("灏忚鎳堣閭瑜� 鎳堣煿 EEPROM")
#define MSG_RESTORE_FAILSAFE                _UxGT("灏忔枩瑜夎姱瑜� EEPROM")
#define MSG_INIT_EEPROM                     _UxGT("琚犺柂鎳堣. EEPROM")
#define MSG_REFRESH                         _UxGT("琚ㄦ枩钖姱鑳佹噲瑜岃")
#define MSG_WATCH                           _UxGT("琚ㄦ枩锜硅姱瑜�")
#define MSG_PREPARE                         _UxGT("琚涙娉勮瑜岃儊鎳堣")
#define MSG_TUNE                            _UxGT("琚ч偑瑜嬭瑜夎姱娉勬郴鎳�")
#define MSG_PAUSE_PRINT                     _UxGT("琚╅偑瑜嶈煿閭� 閿屾瑜旈偑瑜屾噲")
#define MSG_RESUME_PRINT                    _UxGT("琚╄鑺啓鑺阿鍗告噲瑜岃 閿屾瑜旈偑瑜岃")
#define MSG_STOP_PRINT                      _UxGT("琚ㄨ瑜岄偑钖姱鑳佹噲瑜岃 閿屾瑜旈偑瑜岃")
#define MSG_CARD_MENU                       _UxGT("琚ㄦ枩锜硅姱瑜� 娉婚偑瑜夎瑜�")
#define MSG_NO_CARD                         _UxGT("琚ф瑜� 娉婚偑瑜夎瑜�")
#define MSG_DWELL                           _UxGT("灏忚姱钖�...")
#define MSG_USERWAIT                        _UxGT("琚╄鑺啓鑺阿鍗告噲瑜岃...")
#define MSG_PRINT_PAUSED                    _UxGT("琚╂瑜旈偑瑜岃 鑺瑜岄偑钖姱鑳佽阿姊拌柂閭�")
#define MSG_RESUMING                        _UxGT("琚欒姱锜硅姱鏂滆柂鑺儊璋㈡钖噲姊�...")
#define MSG_PRINT_ABORTED                   _UxGT("琚ㄨ灞戞钖偑 閿屾瑜旈偑瑜屾噲")
#define MSG_NO_MOVE                         _UxGT("琚ф瑜� 鍐欒儊鎳堝嵏姊拌柂鎳堣.")
#define MSG_KILLED                          _UxGT("鏍¤琚犲瓭琚�.")
#define MSG_STOPPED                         _UxGT("琚ㄥ皬瀛濊琚цⅷ琚欒ⅴ琚濊ⅶ琚�.")
#define MSG_CONTROL_RETRACT                 _UxGT("琚欒瑜熻皭鎳堣儊閭柂鎳堟 mm")
#define MSG_CONTROL_RETRACT_SWAP            _UxGT("琚欒瑜熻皭. 瑜嬪睉姊拌柂瑜� mm")
#define MSG_CONTROL_RETRACTF                _UxGT("琚欒瑜熻皭鎳堣儊閭柂鎳堟 V")
#define MSG_CONTROL_RETRACT_ZLIFT           _UxGT("琚欒瑜熻皭. 閿岃瑜樺嵏娉婚偑 mm")
#define MSG_CONTROL_RETRACT_RECOVER         _UxGT("琚欒姱锜硅儊瑜夐偑瑜� mm")
#define MSG_CONTROL_RETRACT_RECOVER_SWAP    _UxGT("琚欒姱锜硅儊瑜夐偑瑜� 瑜嬪睉姊拌柂瑜� mm")
#define MSG_CONTROL_RETRACT_RECOVERF        _UxGT("琚欒姱锜硅儊瑜夐偑瑜�  V")
#define MSG_AUTORETRACT                     _UxGT("琚楄儊瑜岃姱 琚欒瑜熻皭鎳堣儊閭柂鎳堟")
#define MSG_FILAMENTCHANGE                  _UxGT("灏忓睉姊拌柂閭� 閿岃瑜嶈娉婚偑")
#define MSG_INIT_SDCARD                     _UxGT("琚犺柂鎳堣. 娉婚偑瑜夎瑜�")
#define MSG_CNG_SDCARD                      _UxGT("灏忓睉姊拌柂鎳堣瑜� 娉婚偑瑜夎瑜�")
#define MSG_ZPROBE_OUT                      _UxGT("Z 鍐欓偑瑜岃鎳堟郴 鑳佽柂姊� 瑜嬭鑺阿閭�")
#define MSG_BLTOUCH                         _UxGT("BLTouch")
#define MSG_BLTOUCH_SELFTEST                _UxGT("瀛濇瑜嬭鎳堣鑺儊閭柂鎳堟 BLTouch")
#define MSG_BLTOUCH_RESET                   _UxGT("灏忔枩瑜夎姱瑜� BLTouch")
#define MSG_BLTOUCH_DEPLOY                  _UxGT("鏍¤瑜岄偑钖姱鑳佹郴閭� BLTouch")
#define MSG_BLTOUCH_STOW                    _UxGT("琚ч偑鏂滄噲鑳佹郴閭� BLTouch")
#define MSG_HOME                            _UxGT("琚╅偑瑜夋郴瑜嶆硠")
#define MSG_FIRST                           _UxGT("閿屾瑜夎儊瑜樻硠")
#define MSG_ZPROBE_ZOFFSET                  _UxGT("灏忓睉姊拌姊拌柂鎳堟 Z")
#define MSG_BABYSTEP_X                      _UxGT("琚︽噲娉昏鑺閭皭 X")
#define MSG_BABYSTEP_Y                      _UxGT("琚︽噲娉昏鑺閭皭 Y")
#define MSG_BABYSTEP_Z                      _UxGT("琚︽噲娉昏鑺閭皭 Z")
#define MSG_ENDSTOP_ABORT                   _UxGT("灏忚閭枩鑺閭阿 娉昏姱钖姊拌儊鎳堟郴")
#define MSG_HEATING_FAILED_LCD              _UxGT("琚偑锜硅姱璋愯姊拌儊 钖 瑜嶅啓閭阿瑜嬭")
#define MSG_ERR_REDUNDANT_TEMP              _UxGT("琚ㄨ鎳堟枩娉婚偑: T 瑜夋鍐�.")
#define MSG_THERMAL_RUNAWAY                 _UxGT("瀛濊琚╄ⅴ琚� 鏍¤琚濊琚楄ⅶ琚犳惡!")
#define MSG_ERR_MAXTEMP                     _UxGT("琚ㄨ鎳堟枩娉婚偑: 瀛� 灞戦偑娉昏.")
#define MSG_ERR_MINTEMP                     _UxGT("琚ㄨ鎳堟枩娉婚偑: 瀛� 灞戞噲钖�.")
#define MSG_ERR_MAXTEMP_BED                 _UxGT("琚ㄨ鎳堟枩娉婚偑:瀛� 灞戦偑娉昏.瑜嬭鑺阿")
#define MSG_ERR_MINTEMP_BED                 _UxGT("琚ㄨ鎳堟枩娉婚偑:瀛� 灞戞噲钖�.瑜嬭鑺阿")
#define MSG_ERR_Z_HOMING                    _UxGT("G28 Z 琚熼偑閿岃姊拌姊拌柂鑺�")
#define MSG_HALTED                          _UxGT("琚╄ⅹ琚犺ⅶ瀛濊琚� 琚ㄥ皬瀛濊琚цⅷ琚欒ⅴ琚濊ⅶ")
#define MSG_PLEASE_RESET                    _UxGT("琚ч偑鍗稿睉鎳堣姊� 瑜夋瑜嬫瑜�")
#define MSG_SHORT_DAY                       _UxGT("鍐�") // One character only
#define MSG_SHORT_HOUR                      _UxGT("瑜�") // One character only
#define MSG_SHORT_MINUTE                    _UxGT("灞�") // One character only
#define MSG_HEATING                         _UxGT("琚ч偑璋愯姊拌儊閭 瑜嬭姱閿岃阿鑺�...")
#define MSG_HEATING_COMPLETE                _UxGT("琚ч偑璋愯姊拌儊 鑳佽閿岃姱璋㈣柂姊拌柂")
#define MSG_BED_HEATING                     _UxGT("琚ч偑璋愯姊拌儊閭 瑜嬭鑺阿")
#define MSG_BED_DONE                        _UxGT("灏忚鑺阿 瑜夐偑锜硅姱璋愯姊拌")
#define MSG_DELTA_CALIBRATE                 _UxGT("琚ｉ偑璋㈡噲鏂滆鑺儊娉婚偑 Delta")
#define MSG_DELTA_CALIBRATE_X               _UxGT("琚ｉ偑璋㈡噲鏂滆鑺儊閭瑜� X")
#define MSG_DELTA_CALIBRATE_Y               _UxGT("琚ｉ偑璋㈡噲鏂滆鑺儊閭瑜� Y")
#define MSG_DELTA_CALIBRATE_Z               _UxGT("琚ｉ偑璋㈡噲鏂滆鑺儊閭瑜� Z")
#define MSG_DELTA_CALIBRATE_CENTER          _UxGT("琚ｉ偑璋㈡噲鏂滆鑺儊閭瑜� 瑜戞钖瑜�")
#define MSG_DELTA_SETTINGS                  _UxGT("琚╄姱娉�. 钖偑瑜嬭瑜夎姱娉勬郴鎳� Delta")
#define MSG_DELTA_AUTO_CALIBRATE            _UxGT("琚楄儊瑜岃姱 娉婚偑璋㈡噲鏂滆鑺儊娉婚偑")
#define MSG_DELTA_HEIGHT_CALIBRATE          _UxGT("琚熼偑鍐欓偑瑜岃 鑳佽瑜嬭姱瑜岃 Delta")
#define MSG_INFO_MENU                       _UxGT("琚� 閿岃鎳堣柂瑜屾瑜夋")
#define MSG_INFO_PRINTER_MENU               _UxGT("琚犺柂瑜�. 鑺� 閿岃鎳堣柂瑜屾瑜夋")
#define MSG_3POINT_LEVELING                 _UxGT("琚ｉ偑璋㈡噲鏂滆鑺儊娉婚偑 3-瑜� 瑜岃姱瑜旀娉�")
#define MSG_LINEAR_LEVELING                 _UxGT("琚ユ噲钖娉勮柂閭 娉婚偑璋㈡噲鏂滆鑺儊娉婚偑")
#define MSG_BILINEAR_LEVELING               _UxGT("琚樻噲璋㈡噲钖娉勮柂閭 娉婚偑璋㈡噲鏂滆.")
#define MSG_UBL_LEVELING                    _UxGT("琚ｉ偑璋㈡噲鏂滆鑺儊娉婚偑 UBL")
#define MSG_MESH_LEVELING                   _UxGT("琚ｉ偑璋㈡噲鏂滆鑺儊娉婚偑 瑜嬫瑜屾郴鎳�")
#define MSG_INFO_STATS_MENU                 _UxGT("灏忚閭鎳堣瑜屾噲娉婚偑 閿岃鎳堣柂瑜屾瑜夐偑")
#define MSG_INFO_BOARD_MENU                 _UxGT("琚犺柂瑜庤姱瑜夊睉閭鎳堣 鑺� 閿岃阿閭姊�")
#define MSG_INFO_THERMISTOR_MENU            _UxGT("瀛濇瑜夊睉鎳堣瑜岃姱瑜夎")
#define MSG_INFO_EXTRUDERS                  _UxGT("鍗忔郴瑜嬭瑜夎鍐欐瑜夎")
#define MSG_INFO_BAUDRATE                   _UxGT("琚樿姱鍐�")
#define MSG_INFO_PROTOCOL                   _UxGT("琚╄鑺鑺郴鑺阿")
#define MSG_CASE_LIGHT                      _UxGT("琚ｈ姱瑜夐攲瑜嶈钖姱姊� 鑺鑳佹瑜栨钖噲姊�")
#define MSG_CASE_LIGHT_BRIGHTNESS           _UxGT("鎼鸿娉昏姱瑜嬭瑜� 鑺鑳佹瑜栨钖噲瑜�")
#if LCD_WIDTH >= 20
  #define MSG_INFO_COMPLETED_PRINTS         _UxGT("琚熼偑娉昏姱钖姊拌柂鑺�")
  #define MSG_INFO_PRINT_TIME               _UxGT("琚╄姱璋㈣柂鑺 鑳佽姊板睉瑜� 閿屾瑜旈偑瑜屾噲")
  #define MSG_INFO_PRINT_FILAMENT           _UxGT("琚涜阿鎳堣柂钖偑 瑜庢噲璋㈤偑灞戞钖閭�")
#else
  #define MSG_INFO_PRINT_COUNT              _UxGT("琚ㄨ閿屾瑜旈偑瑜屾郴鑺儊")
  #define MSG_INFO_COMPLETED_PRINTS         _UxGT("琚熼偑娉昏姱钖姊拌柂鑺�")
  #define MSG_INFO_PRINT_TIME               _UxGT("琚欒姊拌皭鑺�")
  #define MSG_INFO_PRINT_LONGEST            _UxGT("琚ч偑鎳堟枩鑺阿瑜滆姊版")
  #define MSG_INFO_PRINT_FILAMENT           _UxGT("琚欒鍐欓偑鑳佽阿姊拌柂鑺�")
#endif
#define MSG_INFO_MIN_TEMP                   _UxGT("琚︽噲钖�. 瀛�")
#define MSG_INFO_MAX_TEMP                   _UxGT("琚﹂偑娉昏. 瀛�")
#define MSG_INFO_PSU                        _UxGT("琚樿阿鑺郴 閿屾噲瑜岄偑钖噲瑜�")
#define MSG_DRIVE_STRENGTH                  _UxGT("灏忔噲璋㈤偑 閿岃鎳堣儊鑺啓閭�")
#define MSG_DAC_PERCENT                     _UxGT("琚╄鎳堣儊鑺啓 %")
#define MSG_DAC_EEPROM_WRITE                _UxGT("琚熼偑閿屾噲瑜嬫噲 DAC EEPROM")
#define MSG_FILAMENT_CHANGE_HEADER          _UxGT("琚╄鏁堣瀛濋瀷 琚ㄥ皬瀛濊琚цⅷ琚欒ⅴ琚濊ⅶ琚�")
#define MSG_FILAMENT_CHANGE_OPTION_HEADER   _UxGT("琚ㄨⅸ绗戣琚� 琚欒ⅷ琚熻ⅷ琚樿ⅶ琚ㄨ琚ヨ琚ц鎼�:")
#define MSG_FILAMENT_CHANGE_OPTION_EXTRUDE  _UxGT("琚欒鍐欓偑鑳佹噲瑜岃 姊拌瑜�")
#define MSG_FILAMENT_CHANGE_OPTION_RESUME   _UxGT("琚欒姱锜硅姱鏂滆柂鑺儊鎳堣瑜� 閿屾瑜旈偑瑜岃")
#define MSG_FILAMENT_CHANGE_MINTEMP         _UxGT("琚︽噲钖�. 瑜屾灞戦攲姊拌閭瑜嶈閭�")
#define MSG_FILAMENT_CHANGE_NOZZLE          _UxGT("  灏忚姱閿岃阿閭�: ")
//
// Filament Change screens show up to 3 lines on a 4-line display
//                        ...or up to 2 lines on a 3-line display
//
#if LCD_HEIGHT >= 4
  #define MSG_FILAMENT_CHANGE_INIT_1      _UxGT("琚ㄥ嵏鎳堝啓閭硠瑜屾")
  #define MSG_FILAMENT_CHANGE_INIT_2      _UxGT("钖偑瑜旈偑璋㈤偑 瑜嬪睉姊拌柂瑜�")
  #define MSG_FILAMENT_CHANGE_INIT_3      _UxGT("瑜庢噲璋㈤偑灞戞钖閭�")
  #define MSG_FILAMENT_CHANGE_UNLOAD_1    _UxGT("琚ㄥ嵏鎳堝啓閭硠瑜屾")
  #define MSG_FILAMENT_CHANGE_UNLOAD_2    _UxGT("鑳佽璋愯瑜嶈煿娉绘噲 瑜庢噲璋㈤偑灞戞钖閭�")
  #define MSG_FILAMENT_CHANGE_INSERT_1    _UxGT("琚欒瑜岄偑鑳佽瑜屾 瑜庢噲璋㈤偑灞戞钖")
  #define MSG_FILAMENT_CHANGE_INSERT_2    _UxGT("鎳� 钖偑鍗稿睉鎳堣姊� 娉昏柂鑺攲娉昏")
  #define MSG_FILAMENT_CHANGE_INSERT_3    _UxGT("鍐欒阿瑜� 閿岃鑺啓鑺阿鍗告钖噲瑜�...")
  #define MSG_FILAMENT_CHANGE_HEAT_1      _UxGT("琚ч偑鍗稿睉鎳堣姊� 娉昏柂鑺攲娉昏 鍐欒阿瑜�")
  #define MSG_FILAMENT_CHANGE_HEAT_2      _UxGT("钖偑璋愯姊拌儊閭� 瑜嬭姱閿岃阿閭�...")
  #define MSG_FILAMENT_CHANGE_HEATING_1   _UxGT("琚ч偑璋愯姊拌儊 瑜嬭姱閿岃阿閭�")
  #define MSG_FILAMENT_CHANGE_HEATING_2   _UxGT("琚炲啓鎳堣姊�...")
  #define MSG_FILAMENT_CHANGE_LOAD_1      _UxGT("琚ㄥ嵏鎳堝啓閭硠瑜屾")
  #define MSG_FILAMENT_CHANGE_LOAD_2      _UxGT("锜归偑璋愯瑜嶈煿娉绘噲 瑜庢噲璋㈤偑灞戞钖閭�")
  #define MSG_FILAMENT_CHANGE_RESUME_1    _UxGT("琚ㄥ嵏鎳堝啓閭硠瑜屾")
  #define MSG_FILAMENT_CHANGE_RESUME_2    _UxGT("鑳佽姱锜硅姱鏂滆柂鑺儊璋㈡钖噲瑜�")
#else // LCD_HEIGHT < 4
  #define MSG_FILAMENT_CHANGE_INIT_1      _UxGT("琚ㄥ嵏鎳堝啓閭硠瑜屾...")
  #define MSG_FILAMENT_CHANGE_UNLOAD_1    _UxGT("琚欒璋愯瑜嶈煿娉婚偑...")
  #define MSG_FILAMENT_CHANGE_INSERT_1    _UxGT("琚欒瑜岄偑鑳佽 鎳� 钖偑鍗稿睉鎳�")
  #define MSG_FILAMENT_CHANGE_HEATING_1   _UxGT("琚ч偑璋愯姊拌儊...")
  #define MSG_FILAMENT_CHANGE_LOAD_1      _UxGT("琚熼偑璋愯瑜嶈煿娉婚偑...")
  #define MSG_FILAMENT_CHANGE_EXTRUDE_1   _UxGT("琚欒鍐欓偑鑳佽阿鎳堣儊閭柂鎳堟...")
  #define MSG_FILAMENT_CHANGE_RESUME_1    _UxGT("琚欒姱锜硅姱鏂滆柂鑺儊璋㈡钖噲姊�...")
#endif // LCD_HEIGHT < 4

#endif // LANGUAGE_RU_H


